### ISSUE TITLE
Coding Challange : Visual representation for audio files

### ISSUE THREAD

**Issue by emrebicer** [CodingTrain/website#1010]
Hi, is it possible to somehow use an audio file for image processing.What i am trying to do is take a file from the user like an mp3 , mp4 file and create visual representation.(it could be waves or circles moving according to songs recent volume or frequency?).Also what would be cooler is to create different shapes for each audio in the song.Like a circle that vibrates according to vocal and a line that vibrates according to the bass of the song.

**Comment by Fraasi** [comment]
Shiffman did a bunch of videos on this topic few years ago. I think you will find [this playlist](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6aFcVjlDAkkGIixw70s7jpW) interesting.

**Comment by meiamsome** [comment]
Closing as per the above. If that does not answer your suggestion, please feel free to re-post in the [Rainbow Topics](https://github.com/CodingTrain/Rainbow-Topics) repository
