### ISSUE TITLE
Need help to get word from text

### ISSUE THREAD

**Issue by gustavon1973** [CodingTrain/website#1033]
Hi,  your code 1.4: Getting Text from User: Loading a Text File - Programming with Text is working fine for me. Thanks.
Now, I just would like to select a file(or multiple files) and the code will display only the next word from the file(s).  
For example, the code will be set to search for the word "username" or "auth user".  So, I select raibow.txt and if this file contains the word "username" or "auth user " it will display the next work.
in the file rainbow.txt it contains White light .......  The code will be setup to display only light 
This is my code.

function fileLoaded(data) {
  createP(join(data, "<br/>"));
}

function fileSelected(file) {
  //createP("Filename: " + file.name);

  createP("Filename: " + file.name);
  var s = file.data();
  var u = /username/g;
  var matches = u.match(s); 
  if (file.type == "text") {
    for (var i = 0; i <matches.length; i++)
    createP(matches[i]);
  //if (file.type == "text") {
    //createP(file.data);
    
  } else {
    createP("I need a text file.");
  }
  // console.log(file);
}

function setup() {
  noCanvas();

  createFileInput(fileSelected);

  var button = select("#loadfile");
  button.mousePressed(loadFile);

  // console.log(txt);
}

thanks 
Gustavo

**Comment by KobeLiesenborgs** [comment]
Hey Gustavon!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

P.S. Sorry for the late reply, we didn't use the issue section of this repository for a long while.

Hope to see you there!
