### ISSUE TITLE
how do you visualize a recursive sorting algorithm with processing

### ISSUE THREAD

**Issue by GypsyDangerous** [CodingTrain/website#1037]
i am working on the coding challenge where Dan visualized bubble sort, I want to visualize faster algorithm but many of the fast algorithms are recursive and i don't know how to visualize all the steps because recursion happens all at once in the draw loop. How would i do it?

**Comment by Paladorn** [comment]
A solution could be like that:
-Create a global variable (a list of tuples)
-Make the sort and add every change in that list
-And in draw, you just have to do each frame one instruction.
(Don't forget to copy the initial list of values at the beginning, to have it now and redo the sort in draw
