### ISSUE TITLE
Displaying gif on canvas

### ISSUE THREAD

**Issue by emrebicer** [CodingTrain/website#1058]
I have tried image function with p5 but it just showed the initial image of the gif not the entire animation, any advice?

**Comment by gruselhaus** [comment]
@emrebicer 
Here's a demo: https://editor.p5js.org/kjhollen/sketches/S1bVzeF8Z
Maybe this will help you.

**Comment by emrebicer** [comment]
Thank you for the answer :)

**Comment by meiamsome** [comment]
In addition, there is this open issue on p5 to get animations working natively: https://github.com/processing/p5.js/issues/3380

**Comment by shiffman** [comment]
Also, check out this library!

https://github.com/wenheLI/p5.gif/
