### ISSUE TITLE
p5.js tutorials 1+

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#1091]
Regarding #1074 (thank you @simon-tiger and @meiamsome!) I just noticed that since this contribution originated some time ago I have since added newer p5.js tutorials that include the web editor!

https://www.youtube.com/playlist?list=PLRqwX-V7Uu6Zy51Q-x9tMWIv9cueOFTFA

So we should probably replace the video id's, descriptions, etc.!

**Comment by meiamsome** [comment]
Yep, I noticed this too after I had already merged, which is why I left the other PRs open for review. I'll put up a fixing pr in a bit
