### ISSUE TITLE
Flood fill animation

### ISSUE THREAD

**Issue by drinramadani-code** [CodingTrain/website#1139]
So at some point in the video Daniel Shiffman said that we could animate the floodFill
The original code
`this.floodFill();`
instead we should say:
`setTimeout(() => {
      this.floodFill();
    }, 450);`
Just so the floodFill doesn't happen instantly

**Comment by GypsyDangerous** [comment]
here is the coding challenge with your suggestion https://editor.p5js.org/davidgraygs4@gmail.com/sketches/17pi24WsW

**Comment by jonnytest1** [comment]
I like a timeout of 0 best especially with larger grids
https://github.com/CodingTrain/website/issues/1470

I wouldnt use a w below 8 tohugh otherwise it gets really laggy
