### ISSUE TITLE
Simulation of a four lbar linkage mechanism

### ISSUE THREAD

**Issue by Vako9898** [CodingTrain/website#1180]
Good Day everybody, I've been watching the coding train for some days and since I'm studying mechanical engineering I've decided to try and make a simulation of a four bar linkage mechanism, however I've been facing some issues with the code, my main issue right now is that the link four according to the code never changes lenght (and it shouldn't) however the line drawn does, if someone could lend me a hand on this I'd be glad

I've comment the code both in english and spanish

[Mecanismos_2.zip](https://github.com/CodingTrain/website/files/2934064/Mecanismos_2.zip)

**Comment by KobeLiesenborgs** [comment]
Hey Vako!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

P.S. Sorry for the late reply, we didn't use the issue section of this repository for a long while.

Hope to see you there!
