### ISSUE TITLE
Coding Challenge : Langton's Ant in processing

### ISSUE THREAD

**Issue by Tushar00001** [CodingTrain/website#1182]
Hello Dan, here is a coding challenge for you! Try to code the Langton's Ant in processing !!

For Reference : -
http://mathworld.wolfram.com/LangtonsAnt.html
(wiki) : https://en.wikipedia.org/wiki/Langton%27s_ant

(video for those who want clarification) : https://www.youtube.com/watch?v=1X-gtr4pEBU
(live demo) : http://www.langtonant.com

(check out this wonderful work!!) : https://rosettacode.org/wiki/Langton%27s_ant#Processing

**Comment by gruselhaus** [comment]
This challenge exists 🚂
Check out https://thecodingtrain.com/CodingChallenges/089-langtonsant.html
