### ISSUE TITLE
Happy Holi!

### ISSUE THREAD

**Issue by anuraghazra** [CodingTrain/website#1221]
## Happy Holi!

just made this, i think it is cool so i shared it here :smile: 

demo: https://anuraghazra.github.io/Verly.js/examples/typography/

made with verly.js: https://github.com/anuraghazra/Verly.js

![Verly js Typography](https://user-images.githubusercontent.com/35374649/54768634-92171d00-4c25-11e9-9a63-f69d029b38eb.png)

BTW some letters are still missing i'm working on this verly.js physics engine. if anyone have any ideas to make the typography better please make a PR or create an issue.

i'm using a grid to make the points and then calculate the distance from each points to join them arbitrarily.

**Comment by dominicrann61** [comment]
Hi,
Thats awesome.
Great work!!

**Comment by anuraghazra** [comment]
Oh! Thanks!!

**Comment by Rashmi-278** [comment]
Thats Amazing ! keep up the good work

**Comment by anuraghazra** [comment]
Thank you
