### ISSUE TITLE
Didnt have "Search Bar" and "Search Results" Feature throughout website

### ISSUE THREAD

**Issue by sahiljindalthebest** [CodingTrain/website#1223]
Unable to search any specific video via "youtube title" or "any specific challenge no". I especially tried searching about "coding challenge for mandelbrot set" but forced to search via Youtube.

Imo, the search bar should be located at the right top corner of the website

**Comment by gruselhaus** [comment]
@sahiljindalthebest Thank you for this annotation. Unfortunately the current website does not have a search bar. We are really looking forward to add this feature to the new website. 

For reference: https://github.com/CodingTrain/project-trainsite/issues/2
