### ISSUE TITLE
Recommendation: add direct links in youtube videos to the webpage for that coding challenge

### ISSUE THREAD

**Issue by GypsyDangerous** [CodingTrain/website#1257]
I think it would be easier for people to find older challenges if there was a link that went directly to the page of the challenge in the video's description.

**Comment by shiffman** [comment]
Hi @GypsyDangerous! Do you mean links in the YouTube descriptions themselves or links on thecodingtrain.com? I need to do a big pass over all of the YouTube descriptions to update all the links, etc.

**Comment by gruselhaus** [comment]
Maybe we can edit video descriptions using the official youtube api in the future? 

https://developers.google.com/youtube/v3/docs/videos/update

**Comment by GypsyDangerous** [comment]
@shiffman I mean a link in the video's description to the page on the thecodingtrain.com website for that specific coding challenge.

**Comment by GypsyDangerous** [comment]
This has been done 😃
