### ISSUE TITLE
How to add p5/Processing ports?

### ISSUE THREAD

**Issue by jnsjknn** [CodingTrain/website#1296]
I would be happy to help with porting the coding challenges related to #267. 

Should I fork the repository, make add the port directly to "website/CodingChallenges/CC_XXX_NameOfChallenge" and make a pull request or should I do it like the community contributions are done as described in [the Community Contributions Guide](https://github.com/CodingTrain/website/wiki/Community-Contributions-Guide)?

**Comment by gruselhaus** [comment]
@jnsjknn Thank you for asking!

There are two options:
#### 1. Code Portation:
The ported code should not have additional edits or enhancements, it is just a plain portation to the other language. In that case you should add those ported files to the folder in `CodingChallenges`. You are welcome to add a comment in the code that you have ported the Coding Challenge. After receiving the "go for merge" from @shiffman, we will merge your pull request.

#### 2. Community Contribution
You are always welcome to add your "version" of a specific Coding Challenge. Extra information: [Community Contributions Guide](https://github.com/CodingTrain/website/wiki/Community-Contributions-Guide)

I hope to have your question answered.

Nico

**Comment by jnsjknn** [comment]
Thank you. This answers my question.
