### ISSUE TITLE
Confused - Perlin noise loops challenge

### ISSUE THREAD

**Issue by JohnyDL** [CodingTrain/website#1309]
I was going to add a contribution but I got really confused, both the web pages for the two perlin noise loop challenges 136.1 and 136.2 seem to be drawing their community contributions from the same location, is this normal/working correctly? should I go with the flow and post on the 136.1 md, or not, when my contribution is for the second the 136.2 challenge?

Relevant links:
https://thecodingtrain.com/CodingChallenges/136.1-polar-perlin-noise-loops.html
https://thecodingtrain.com/CodingChallenges/136.2-perlin-noise-gif-loops.html
https://github.com/CodingTrain/website/edit/master/_CodingChallenges/136.1-polar-perlin-noise-loops.md
https://github.com/CodingTrain/website/blob/master/_CodingChallenges/136.2-perlin-noise-gif-loops.md

(so I don't lose it)
>   - title: "Moving a noise circle in a circle"
>    author:
>      name: "John 'JohnyDL' Lewis"
>    url: "https://editor.p5js.org/JohnyDL/full/wZv0CEz7c"
>    source: "https://editor.p5js.org/JohnyDL/sketches/wZv0CEz7c"

**Comment by gruselhaus** [comment]
Hello @JohnyDL,
thank you for this question. Yes, currently our systems allows only contributions to the first part of a video. All other parts fetch the contributions from the first part.

**Comment by JohnyDL** [comment]
if that's the way it works then I've edited my stuff in (I would have thought that each part of each challenge would have it's own contributions but I stand corrected)
