### ISSUE TITLE
SyntaxError: Identifier 'cols' has already been declared

### ISSUE THREAD

**Issue by CodingMarkfirst** [CodingTrain/website#1317]
Well, i had a problem making Conways Game of Life on Javascript, but suddenly it showed this error: "SyntaxError: Identifier 'cols' has already been declared". I am asking if anyone can see the problem in this code.
```
function make2DArray(cols, rows) {
  let arr = new Array(cols);
  for (let i = 0; i < arr.length; i++) {
      arr[i] = new Array(rows);
}
return arr;
}


let grid;
let cols = 10;
let rows = 10;

function setup() {

  grid = make2DArray(cols, rows)
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      grid[i][j] = floor(random(2));
    }
  }
}
```

**Comment by gruselhaus** [comment]
I can not reproduce this. Do you declare `cols` maybe somewhere else as well?

**Comment by CodingMarkfirst** [comment]
I don't know, maybe you can see it. Please tell me where the problem is because that would be really helpful. Thanks! 

```

let grid;
let cols;
let rows;
let resolution = 20;

function make2DArray(cols, rows) {
  let arr = new Array(cols);
  for (let i = 0; i < arr.length; i++) {
      arr[i] = new Array(rows);
     }
return arr;
}

function setup() {
  createCanvas(600, 400);
  cols = width / resolution;
  rows = height / resolution;
  grid = make2DArray(cols, rows)
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      grid[i][j] = floor(random(2));
    }
  }
}

function draw() {
  background(0);
  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      let x = i * resolution;
      let y = j * resolution;
      if (grid[i][j] == 1) {
        fill(255);
        stroke(0);
        rect(x, y, resolution, resolution);
      }
    }
  }
}
```

**Comment by ArtemSer** [comment]
This code is correct and works. Have you any other `js` files included to your `index.html`? 
Look for `let cols` in your project, I think, you should find a second declaration or unnecessary `let`.

**Comment by CodingMarkfirst** [comment]
> This code is correct and works. Have you any other `js` files included to your `index.html`?
> Look for `let cols` in your project, I think, you should find a second declaration or unnecessary `let`.

No sorry, I don't have any other _js_ files linked to my HTML file. But I have found a _let cols_ in my project and I'm about to check if its working. Thank you for your tip!

**Comment by CodingMarkfirst** [comment]
It runs! Thank y' all for your cooperation!
