### ISSUE TITLE
Suggestion - Add Community Reference Material Section to CC Pages

### ISSUE THREAD

**Issue by figraham** [CodingTrain/website#1340]
I'd like to suggest adding a section to the coding challenge pages for community members to add references to other educational videos, articles, or projects (that are not their own).

I think some of this happens in the youtube comments but I've found it can get lost among other comments. It might be a valuable way for people to find additional resources when working on projects.

I had this idea after the latest coding challenge on ray casting when it reminded me of a video about doing the same thing using a command line in c++. Having a section of related references might be a good way to diversify the coding challenge pages and provide options for those working in other languages (programing or non-programming).

[Link to the previously mentioned video](https://www.youtube.com/watch?v=xW8skO7MFYw&t=31s) in case someone is interested.

This idea relates to #1092

**Comment by gruselhaus** [comment]
Thank you @figraham. I've opened a PR with an implementation. Feel free to review.

**Comment by shiffman** [comment]
This is such a great idea @figraham thank you for suggesting! And thank you @gruselhaus for implementing!! ❤️ ❤️

**Comment by gruselhaus** [comment]
@figraham The feature has been deployed. You can now add references like following: 
```yaml
community_references:
  - title: "Test"
    author: 
      name: "Example Name"
      url: "https://example.url"
    url:  "https://example.url"
```
