### ISSUE TITLE
createCapture(VIDEO) not working with minified libraries on iOS

### ISSUE THREAD

**Issue by blackwolf08** [CodingTrain/website#1379]
createCapture(VIDEO) shows a black screen on iPhone running latest software updates (iOS 12.3), updating libraries to non-minified versions does the trick! I have raised the issue in p5.js, this is an issue with the minified files and hope it would be updated in the coming versions

**Comment by gruselhaus** [comment]
https://github.com/processing/p5.js/issues/3763
