### ISSUE TITLE
Made the fluid simulation in C# and added some vorticity confinement

### ISSUE THREAD

**Issue by SuperSimon81** [CodingTrain/website#1391]
Thank you for a great tutorial. 

https://github.com/SuperSimon81/FluidParty/tree/master

**Comment by gruselhaus** [comment]
May I open a PR for you with the contribution, so that the contribution appears on the website?

**Comment by SuperSimon81** [comment]
sure

Den mån 3 juni 2019 kl 22:21 skrev Nico Finkernagel <
notifications@github.com>:
