### ISSUE TITLE
Content Security Policy directive

### ISSUE THREAD

**Issue by pgokhale2000** [CodingTrain/website#1392]
From the Chrome Extension tutorials, I used the code on github for Pop-ups Messaging. When reloading my extension I get the error message 

Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.min.js' because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by gruselhaus** [comment]
@pgokhale2000 Has this issue been resolved?
