### ISSUE TITLE
Breadth-first search: problem with storing nodes to the graph.

### ISSUE THREAD

**Issue by MuhammadSaeedSaad** [CodingTrain/website#1409]
https://stackoverflow.com/questions/56614597/cant-store-data-properly-to-implement-the-breadth-first-search-in-application-l

**Comment by jonnytest1** [comment]
your hasNode method shouldnt abort if the first element wasnt found instead only return false if all of the elements are checked and there is no match

**Comment by KobeLiesenborgs** [comment]
Hey everyone!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

P.S. Sorry for the late reply, we didn't use the issue section of this repository for a long while.

Hope to see you there!
