### ISSUE TITLE
 Error: Failed to link vertex and fragment shaders.

### ISSUE THREAD

**Issue by OJ23** [CodingTrain/website#1427]
Hi there, 
I have been following your machine learning tutorials for ml5.js and am using the code provided on github to train images - however when i get to a certain number it crashes and gives me the error:    

Error: Failed to link vertex and fragment shaders.
    at gn (https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:86899)

    at e.createProgram (https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:102578)

    at https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:212722

    at https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:212936

    at e.getAndSaveBinary (https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:214075)

    at e.compileAndRun (https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:212247)

    at e.batchMatMul (https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:151473)

    at me.engine.runKernel.$a (https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:230573)

    at https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:28277

    at e.scopedRun (https://unpkg.com/ml5@0.2.1/dist/ml5.min.js:35:27896)

Any help would be appreciated!

**Comment by jonnytest1** [comment]
pretty sure that means you ran out of memory oO try keeping the tab manager open to see your gpu/cpu memory  depending on what youre using and dont forget to use dispose on all the tensors

**Comment by OJ23** [comment]
> pretty sure that means you ran out of memory oO try keeping the tab manager open to see your gpu/cpu memory depending on what youre using and dont forget to use dispose on all the tensors

hmm okay il try doing that - what do you mean by using dispose on tensors (sorry im very new to this)

**Comment by jonnytest1** [comment]
ml5 is usually high level enough so you dont have to do the memory management on your own oO which version are you using ? can can you provide an example of yopur code ?

**Comment by OJ23** [comment]
Yeah sure, the version of ml5 im using 2.1 and my code is:
(`<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>KNN Game Controller</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/addons/p5.dom.min.js"></script>
    <script src="https://unpkg.com/ml5@0.2.1/dist/ml5.min.js"></script>
    <script src="sketch.js"></script>
  </head>
  <body></body>
</html>`)



`let video;
let features;
let knn;
let labelP;
let ready = false;
let x;
let y;
let label = 'nothing';

function setup() {
  createCanvas(0,0);
  video = createCapture(VIDEO);
  video.size(700,500);
  features = ml5.featureExtractor('MobileNet', modelReady);
  knn = ml5.KNNClassifier();
  labelP = createP('Training Data Required');
  labelP.style('font-size', '32pt');
  x = width / 2;
  y = height / 2;
}

function goClassify() {
  const logits = features.infer(video);
  knn.classify(logits, function(error, result) {
    if (error) {
      console.error(error);
    } else {
      label = result.label;
      labelP.html(result.label);
      goClassify();
    }
  });
}

function keyPressed() {
  const logits = features.infer(video);
  if (key == '1') {
    knn.addExample(logits, 'The Car Park is Currently Empty: Many Spaces Available!');
    console.log('Empty');
  } else if (key == '2') {
    knn.addExample(logits, 'The Car Park is Currently Filling Up: Limited Spaces Available!');
    console.log('Half-Full');
  } else if (key == '3') {
    knn.addExample(logits, 'The Car Park is Nearly Full: Very Limited Spaces Available!');
    console.log('Nearly Full');
  } else if (key == '4') {
    knn.addExample(logits, 'The Car Park is Currently Full: No Spaces Available!');
    console.log('Full');
  } else if (key == 's') {
    save(knn, 'model.json');
    //knn.save('model.json');
  }
}

function modelReady() {
  console.log('model ready!');
  // Comment back in to load your own model!
  // knn.load('model.json', function() {
  //   console.log('knn loaded');
  // });
}

function draw() {


  if (label == 'empty') {
    x--;
  } else if (label == 'right') {
    x++;
  } else if (label == 'up') {
    y--;
  } else if (label == 'down') {
    y++;
  }

  //image(video, 0, 0);
  if (!ready && knn.getNumLabels() > 0) {
    goClassify();
    ready = true;
  }
}

// Temporary save code until ml5 version 0.2.2
const save = (knn, name) => {
  const dataset = knn.knnClassifier.getClassifierDataset();
  if (knn.mapStringToIndex.length > 0) {
    Object.keys(dataset).forEach(key => {
      if (knn.mapStringToIndex[key]) {
        dataset[key].label = knn.mapStringToIndex[key];
      }
    });
  }
  const tensors = Object.keys(dataset).map(key => {
    const t = dataset[key];
    if (t) {
      return t.dataSync();
    }
    return null;
  });
  let fileName = 'myKNN.json';
  if (name) {
    fileName = name.endsWith('.json') ? name : `${name}.json`;
  }
  saveFile(fileName, JSON.stringify({ dataset, tensors }));
};

const saveFile = (name, data) => {
  const downloadElt = document.createElement('a');
  const blob = new Blob([data], { type: 'octet/stream' });
  const url = URL.createObjectURL(blob);
  downloadElt.setAttribute('href', url);
  downloadElt.setAttribute('download', name);
  downloadElt.style.display = 'none';
  document.body.appendChild(downloadElt);
  downloadElt.click();
  document.body.removeChild(downloadElt);
  URL.revokeObjectURL(url);
};`

**Comment by jonnytest1** [comment]
after saveFile call 

`tensors.forEach(t=>t.dispose()) `

that should help

**Comment by OJ23** [comment]
Even if i try that though, i dont think it would work because the ml5.js cant take files above 4MB if i tried to save and reload the Json fiile.

**Comment by jonnytest1** [comment]
you have goClassify in both the Draw Function which gets called about 30 times per second and (though async ) in goClassifiy itself

**Comment by jonnytest1** [comment]
```

function goClassify() {
    const logits = features.infer(video);
    knn.classify(logits, function(error, result) {
         logits.dispose()
        if(error) {
            console.error(error);
        } else {
            debugger;
            label = result.label;
            labelP.html(result.label);
            goClassify();
        }
    });
}
```
