### ISSUE TITLE
Loading JSON data from a URL have a Problem

### ISSUE THREAD

**Issue by ArthurSongChina** [CodingTrain/website#1443]
I have followed your youtube lesson about loading JSON data from a URL, and have used the function loadJSON(URL, gotData, "jsonp"); or loadJSON (URL, gotData); both could not load JSON file. 
The error on the console is 
Uncaught (in promise) TypeError: Failed to fetch
and
p5.js:31021 Uncaught (in promise) Error: JSONP request to http://api.open-notify.org/astros.json timed out

Appreciate your help...

**Comment by jonnytest1** [comment]
you probably got another error somewhere above in your console notifiying you about CORS problems. the API in question did not whitelist your domain in  their cors policy . a way around that is by moving your request to a server

**Comment by KobeLiesenborgs** [comment]
Hey everyone!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

P.S. Sorry for the late reply, we didn't use the issue section of this repository for a long while.

Hope to see you there!
