### ISSUE TITLE
Website suggestion: make the blue bar with links fixed so it stays as you scroll down

### ISSUE THREAD

**Issue by GypsyDangerous** [CodingTrain/website#1470]
I was on the tutorial section of the website recently and I was at the bottom of the page and I wanted to get somewhere else so I had to scroll all the way back up to the top to get the link bar and I think it would be more convenient if the link bar stayed with you as you scrolled down.

**Comment by jonnytest1** [comment]
example on how it would look https://raspberrypi.e6azumuvyiabvs9s.myfritz.net/fixednavbarvideo/

**Comment by gruselhaus** [comment]
@jonnytest1 Thank you for this improvement. Feel free to open a PR.

**Comment by GypsyDangerous** [comment]
I'm gonna close this issue because the PR was merged.
