### ISSUE TITLE
merge pipeline error messages

### ISSUE THREAD

**Issue by jonnytest1** [CodingTrain/website#1527]
The error messages are sometimes unhelpful sometimes wriong and sometimes both :P

This one for example (sorry I stole it from someones merge)
says its formatted (IN)correctly at the top in red

additionally msot of the information (maybe except of the filename) is not useful in fixing the error

I would hope to at leasat get the file number if not an example like below for the actual error oO

![error messages](https://user-images.githubusercontent.com/13507796/61997673-5f82a280-b0a5-11e9-93ba-a42cfdb7eb8b.png)

**Comment by gruselhaus** [comment]
Agreed. We could create a troubleshooting guide with all possible errors and fixes. @jonnytest1 what do you think?

**Comment by jonnytest1** [comment]
sorry I only realized later that its the test name but its still unhelpful

**Comment by jonnytest1** [comment]
@gruselhaus for the yaml error its probably more helpful to think of a way to get mroe detaiuled errormessages instead of a general guide but its a stepo in the right direction

**Comment by jonnytest1** [comment]
the match function used in files.js even returns additional parameters like the index where the match was found so we could quite easily expand to display additional information

**Comment by jonnytest1** [comment]
I think I remember @shiffman saying that only the first mach get registered . so we could just collect all the errors and display them at the end as well

**Comment by jonnytest1** [comment]
I wonder if I launched the tests correctly cause I get 361 failed right of the bat oO ?

**Comment by jonnytest1** [comment]
currently it looks like this : 
still looks somewhat confusing but at least there is information
![errormsg](https://user-images.githubusercontent.com/13507796/61999564-23126f00-b0c4-11e9-8419-caf3c5ec1fe7.png)

**Comment by jonnytest1** [comment]
https://github.com/jonnytest1/website/tree/testing 
would be nice if someone could do some testing on linux machines and double check the regex I think its still the way it was before but its hard to test on windows machine (file endings) im also not sure if they worked before tbh (again hard to test on windows)

**Comment by gruselhaus** [comment]
Could you open a PR please. So I can request some reviews.

**Comment by jonnytest1** [comment]
https://github.com/CodingTrain/website/pull/1534

**Comment by jonnytest1** [comment]
hers an example where I added a space after a line 
https://circleci.com/gh/CodingTrain/website/2726?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by meiamsome** [comment]
I wonder if you can raise an error with a custom stack trace inside of the file with the issue so that Jest picks that up and marks it as it would any other file?

**Comment by jonnytest1** [comment]
maybe like this ? https://jestjs.io/docs/en/expect#expectstringmatchingstring-regexp

**Comment by gruselhaus** [comment]
#1534 got merged
