### ISSUE TITLE
Website suggestion: add the Community Contributions section on the tutorial's pages

### ISSUE THREAD

**Issue by GRFreire** [CodingTrain/website#1559]
I made a contribution on one of the 'working-with-data' tutorials ([this one](https://github.com/CodingTrain/website/blob/master/_Tutorials/10-working-with-data/10.2-what-is-json-part-1.md)) and it has already been acepted, but I noted that my contribution is not on the [page](https://thecodingtrain.com/Tutorials/10-working-with-data/10.2-what-is-json-part-1.html), probably because the tutorial's page is not configured to do so.
My suggestion is to add the Community Contributions section on the tutorial's pages.

**Comment by gruselhaus** [comment]
I've just deployed a fix. Should appear on the website in a minute or so.
