### ISSUE TITLE
upper case urls?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#1561]
Is it problematic in the long term that the urls require capitalization?

https://thecodingtrain.com/Tutorials/19-workflow/
https://thecodingtrain.com/CodingChallenges/130.3-fourier-transform-drawing.html

It bothers me visually. . any chance we can change to lower case but upper case ones will still work?

Have I gone mad and I shouldn't worry about this?

**Comment by gruselhaus** [comment]
Unfortunately Jekyll relies on case sensitive URLs. @nilsweb do you have an idea how we could implement a work around? Thinking about jekyll-redirect-from...

**Comment by meiamsome** [comment]
There's this script that will convert to the right case if anyone enters a different case version: https://gist.github.com/sbliven/0ca4dee4e0190a6b3dc7e3d8040cc395

That said, changing all the folders/files to lowercase would still break any links to the actual repositories files, so I wouldn't bother

**Comment by nilsweb** [comment]
Hmm... Good question... 🤔 
I don't really know why they were uppercase to begin with.
Maybe there's some workaround but it wouldn't be pretty.

That's true @meiamsome! It _could_ be fixable by converting the lowercase version to the right case where needed but it would make the already confuse URL-building-extravaganza even less maintainable.

**Comment by shiffman** [comment]
I'm ok with breaking everything and never looking back ☠️

**Comment by nilsweb** [comment]
I'll look into what's all case-sensitive and would be affected and how we might be able to work around it if necessary.

In the end, nice, consistent URLs are _very important_... :smirk: :yum:
