### ISSUE TITLE
What does map do on Drop.js?

### ISSUE THREAD

**Issue by FikriRNurhidayat** [CodingTrain/website#1665]
I wonder what does map do in drop.js, I try to google it, most of them is just a method on array, but in your function it doesn't sound like array methods
[drop.js](https://github.com/CodingTrain/website/blob/master/CodingChallenges/CC_004_PurpleRain/P5/drop.js)

**Comment by gruselhaus** [comment]
Here's the official p5.js reference: https://p5js.org/reference/#/p5/map

**Comment by anuraghazra** [comment]
shiffman's video on the map() function: https://www.youtube.com/watch?v=nicMAoW6u1g
