### ISSUE TITLE
Langstons ant runs too fast

### ISSUE THREAD

**Issue by Wllkrd** [CodingTrain/website#1748]
HI! I am running the Sketch in processing and would like to slow it down to view it's process slower! Currently it runs too fast for me to see. __**Is there any way I can slow it down?**__

![Langstons Ant](https://user-images.githubusercontent.com/56102133/66097394-dafc4680-e563-11e9-842d-bd6606b48e3f.gif)

**Comment by GypsyDangerous** [comment]
@Wllkrd if you are using the same code as the video there should be a for loop that surrounds everything in draw, reduce the number of times that for loop goes.

**Comment by Wllkrd** [comment]
Thanks, I'll try that!

**Comment by Wllkrd** [comment]
That works! Thanks
