### ISSUE TITLE
Cannot locate session 4 of A2Z series.

### ISSUE THREAD

**Issue by a-y-u-s-h** [CodingTrain/website#175]
I'm trying to find session 4 of A2Z series. There's no live stream for session 4, no playlist too. Are they being re-made ?

**Comment by shiffman** [comment]
I moved the code to here:
https://github.com/CodingTrain/Rainbow-Code/tree/master/Courses/A2Z/session04

But it needs to be numbered and matched with the videos (would love any help with this!)

This is also a resource:
https://github.com/CodingTrain/Rainbow-Code/tree/master/Courses/A2Z/session04

**Comment by nilsweb** [comment]
It should now be available here: https://github.com/CodingTrain/website/tree/master/Courses/programming_with_text/session04
