### ISSUE TITLE
How to add p5 web editor port of a coding challenge

### ISSUE THREAD

**Issue by GypsyDangerous** [CodingTrain/website#1807]
I've ported the pixel sorting coding challenge to the p5 web editor and I want to contribute it but I can't find where to add it.

**Comment by shiffman** [comment]
Unfortunately p5 web editor sketches need to be manually added to the coding train account. I'll give @violetcraze the keys and you can maybe coordinate via slack and we can duplicate the sketch. Let's make sure to add a comment in the code to credit you for the porting.

**Comment by GypsyDangerous** [comment]
okay, [here](https://editor.p5js.org/D_Snyder/sketches/qNdanRS0n) is the link to the sketch, i've already added the necessary comments (i think i got them all). I can also share it will violet on slack if i need to.
