### ISSUE TITLE
Adding Backlog of Guest Tutorials

### ISSUE THREAD

**Issue by violetcraze** [CodingTrain/website#1813]
I noticed that the guest tutorials section has fallen behind what's on YouTube. It would be great to back fill some of those videos. We currently only have 6 and 7 in that series. Also it would be great to make them more accessible from the navigation but I'll include that in a navigation issue I'm opening to discuss that and other possible changes.

I'm happy to work on this project but I wanted to give others the opportunity to contribute.

What's needed is to add a `.md` file to the `/_GuestTutorials` folder following the format `###-guest-name-video-title.md` an example would be `006-golan-levin-modulo-operator`.

You can follow this basic structure of an existing page. https://raw.githubusercontent.com/CodingTrain/website/master/_GuestTutorials/006-golan-levin-modulo-operator.md Also refer to a complete coding challenge like Mandelbrot Pi on how to add videos or links sections if appropriate. https://raw.githubusercontent.com/CodingTrain/website/master/_CodingChallenges/141-mandelbrot-pi.md

You can find most if not all of the information about the video in the YouTube description. But it would be great to watch the video and see if anything was missed from that. Be mindful that we don't want to include a the code from the video in our repository, like is normally done with the coding challenges, use the link to code that is in the video description.

If you'd like to claim working on one just leave a comment below so multiple people don't do the same one. Would be great to add 1-5 and 8-11. You can find the full list here: https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bYBG4PsCJpsvMka3boE9pR.

Don't hesitate to ask questions!

**Comment by eecastillo** [comment]
Hi, I would like to help by adding the .md file related to the Guest Tutorial #4

**Comment by emaraan** [comment]
Hi there! I'd like to help by working on the .md file for Guest Tutorial #10

**Comment by mikakruschel** [comment]
Hi! I'd like to help by adding the .md file for the Guest Tutorial 5

**Comment by mikakruschel** [comment]
I just noticed that the link mentioned in the video and in the video's description for the code of the [guest tutorial 9 with Jabril](https://youtu.be/iN3WAko2rL8?t=1238) is broken.

**Comment by mikakruschel** [comment]
And I'm currently writing the .md file for Guest Tutorial 2 and noticed that the link to mojs.io also no longer works.

**Comment by violetcraze** [comment]
@mikakruschel thanks for the heads up on 9. I'll try to track down the code at some point this weekend.

**Comment by Tekman03** [comment]
@violetcraze @mikakruschel I have found the repo on Jabrils' channel and have submitted a PR

**Comment by violetcraze** [comment]
Thanks for your help everyone ♥️💻🚂! I'm gonna close this issue as we've covered all all the numbered guest tutorials.
