### ISSUE TITLE
Navigation bar resizing

### ISSUE THREAD

**Issue by Tekman03** [CodingTrain/website#1834]
Since new buttons have been added to the navigation bar in recent weeks, the bar now over extends on devices in between 750ish px and 550px.

Was wondering if simply putting a new sass var for the breakpoint of the nav at 750px? Maybe setting it to $tablet-big(: 920px) would look the best? Or does somebody want an intermediary step between desktop and mobile?

I am happy to do this if it sounds fine?

**Comment by GypsyDangerous** [comment]
I'm gonna close this because that merge seems to have fixed it, feel free to reopen if needed.
