### ISSUE TITLE
Adding Backlog of Live Streams

### ISSUE THREAD

**Issue by mikakruschel** [CodingTrain/website#1859]
I noticed the streams 127 to 187 are missing on the website. Is there any reason for that? Otherwise, I'll start adding them to the website.

[Live stream playlist on youtube](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bxnFR6no70vlxxuxDEzflz)

**Comment by shiffman** [comment]
Hi @mikakruschel thank you so much for your contributions!!! There is no reason for this, no. The descriptions on YouTube are a bit out of date (ideally they'd each have a timecoded outline of the stream itself as well as links and other references to the topics.) @cdslls is working on YouTube descriptions but we're not at the live streams just yet. Not sure if it's best to make webpages after descriptions are updated or use the webpages as a guide for updating the descriptions. . open to any and all ideas!
