### ISSUE TITLE
Use 'Cache' in GithubAction?

### ISSUE THREAD

**Issue by anuraghazra** [CodingTrain/website#1885]
I don't know if this would improve the speed of the build but i think it would be good idea to add caching

https://github.com/actions/cache
https://github.com/marketplace/actions/cache

https://github.com/CodingTrain/website/blob/9047714309b80e3c96227d9fdd830733ff79a2ab/.github/workflows/ruby.yml#L1

**Comment by gruselhaus** [comment]
Ok, this was a massive performance improvement. Thanks @anuraghazra for this reminder 👍🏻
