### ISSUE TITLE
Teachable Machine on landing page

### ISSUE THREAD

**Issue by mikakruschel** [CodingTrain/website#1901]
Currently, the Teachable Machine videos don't appear on the landing page. Is this intended?

**Comment by shiffman** [comment]
Ordinarily the landing page is for coding challenges (and now cabana also) only, but I would also make an exception for Teachable Machine!

**Comment by mikakruschel** [comment]
Ok. Do you know when you will release the third video? So that I can fix the (planned) release dates in the md files in order for them to appear in the right order on the landing page.

**Comment by shiffman** [comment]
Maybe tomorrow or Monday? It's ready now and am always wondering what the optimal release time is! Let's say Monday?

**Comment by mikakruschel** [comment]
Sounds good! If you want to publish it tomorrow you can still change the date in the md file.
