### ISSUE TITLE
Floodfill function in Minesweeper coding challenge

### ISSUE THREAD

**Issue by sahil-jindal** [CodingTrain/website#1920]
it's not an issue, rather a question...... In the flood fill function of minesweeper....... 

Why are we using?? 
if (i < 0 || i >= cols) continue;  
if (j < 0 || j >= rows) continue; 

for boundary condition where we could simply bound under this if statement

if(i >= 0 && i <= cols && j >= 0 && j <= rows)

And when i tried to run with it... it throws an error of "Cannot read property of undefined (Line no)"

**Comment by violetcraze** [comment]
If I'm looking at the right code. (https://editor.p5js.org/codingtrain/sketches/-mz-ePoqd)

I believe `if(i >= 0 && i < cols && j >= 0 && j < rows)` (slightly different from what's in your post) would do basically the same thing. I think why Dan made the choice to check and then continue, was to avoid doing extra comparisons in the inner loops. Which might make the code slightly faster but you probably won't notice a difference. It's mostly a matter of code style.

I couldn't reproduce a bug in the sketch. We generally try to keep code from the challenges the same so they match the video but if there's a bug then that might be worth fixing or at least adding a comment about.

**Comment by sahil-jindal** [comment]
Thanks for your explanation and thanks for correcting the mistake, I did recognize it after i have posted
