### ISSUE TITLE
Pong Coding Challenge

### ISSUE THREAD

**Issue by sahil-jindal** [CodingTrain/website#1931]
This is my refactored repo on a pong coding challenge. To be honest, I am not sure whatever all bugs are fixed or not.

Major Changes:-
1) Everything is relative to the center of the canvas. (even the calculations lol)
2) Two separate functions "CheckPaddleLeft" and "CheckPaddleRight" merged into a single function "CheckPaddle".

Bugs in the repo:-
1) If puck and paddle both reach the corner of the canvas, puck stucks and vibrates until the paddle is not moved (even though puck's center is out of the canvas).
2) If observed on the low framerates, the puck does not bounce directly from the surface of the paddle, it comes a bit inside the paddle to bounce.
3) When the puck passes the paddle, not only puck but also both the paddle should go back to their original positions.

Work left behind:- Text alignment to show the score.

Anyways, here is my repo:-
[Click here](https://github.com/sahil-jindal/Pong-Game)

**Comment by violetcraze** [comment]
This is great! Thanks for sharing. If you'd like it to be shown on the website you can follow the [community contributions guide](https://thecodingtrain.com/Guides/community-contribution-guide.html) to add it to the [pong webpage](https://thecodingtrain.com/CodingChallenges/067-pong.html).
