### ISSUE TITLE
Missing "view code" "download code" on courses page

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#1941]
Is there a reason what the "view code" or "download code" buttons don't show up on the new ml5.js "train your own neural network" page?

<img width="1318" alt="Screen Shot 2019-11-21 at 2 16 17 PM" src="https://user-images.githubusercontent.com/191758/69369301-d30a7a00-0c69-11ea-8d8b-370a4eddd326.png">

**Comment by gruselhaus** [comment]
Problem found. Will push the fix in a few seconds...

**Comment by gruselhaus** [comment]
10e9800

**Comment by gruselhaus** [comment]
@shiffman the buttons should appear on the website in a few seconds...
