### ISSUE TITLE
Potential issue with latest videos on landing page

### ISSUE THREAD

**Issue by GypsyDangerous** [CodingTrain/website#1947]
I noticed in the latest video section of the landing page that the third video is stuck as the most recent stream that has been added to the website. Is that spot reserved for streams or is it a bug? If it is a bug I am not sure how to fix it cause I'm a beginner at Jekyll. This is also loosely related to the issue of the last stream being added to the website is from last year.
![landing page](https://user-images.githubusercontent.com/45735850/69502234-e2dcc500-0eda-11ea-82dd-75c2c4d21f80.png)

**Comment by gruselhaus** [comment]
Looks like that the spot is reserved for the latest stream https://github.com/CodingTrain/website/blob/09feafa60758080c0a4761a2578b01e7e4bb0c42/landing-page.html#L29

**Comment by shiffman** [comment]
I think I would opt for the latest three videos and maybe ignore the live streams?
