### ISSUE TITLE
"initDevice()" and "depthWidth" not working on Processing3 with kinect1

### ISSUE THREAD

**Issue by Gabirell** [CodingTrain/website#20]
Hi, when I try to compile, processing says that the function "initDevice()" does not exist.
The same with "depthWidth" and "depthHeight": The global variable depthWidth does not exist.

It seems to work on kinect2 but not on kinect1.

Is there another way to select the depth width on a kinect1?

thanks

**Comment by Gabirell** [comment]
I forgot to say that I'm on Yosemite 10.10.5.
;)

**Comment by SetupandDraw** [comment]
same problem for me

**Comment by shiffman** [comment]
This is my fault, it's actually just `.width` and `.height` for kinect v1.  You also don't need the `initDevice()` function. See these examples for more:

https://github.com/shiffman/OpenKinect-for-Processing/tree/master/OpenKinect-Processing/examples/Kinect_v1

Will leave this open as I really need to make v1 versions of the examples here.
