### ISSUE TITLE
Cannot execute teachable machine code in chrome because of CORS problem

### ISSUE THREAD

**Issue by cap-code** [CodingTrain/website#2007]

**Comment by violetcraze** [comment]
Thanks for reporting this. CORS problems can crop up in a couple situations. Did you have a problem with it in the web editor or using local files?

**Comment by cap-code** [comment]
I  used atom text editor and p5 web editor and was using link given by teachable machine

**Comment by DeyvidBG** [comment]
Did someone come up with a solution? I have my files uploaded on the server and everything was working just fine till I got this CORS issue problem and now I cannot run my AI. Thanks in advance.

**Comment by KobeLiesenborgs** [comment]
Hey everyone!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

P.S. Sorry for the late reply, we didn't use the issue section of this repository for a long while.

Hope to see you there!
