### ISSUE TITLE
Mobile Navbar cut off by screen size

### ISSUE THREAD

**Issue by GypsyDangerous** [CodingTrain/website#2023]
After #2011 was merged I was checking out the website on mobile and I noticed that the navbar is cut off by the size of the screen. in portrait mode, it is not a big problem unless you try to open some of the dropdowns like the very last one ![portait mode](https://user-images.githubusercontent.com/45735850/71550950-c2a49800-29a9-11ea-9859-1a4e8ceb7afc.jpg)
the big issue comes when in landscape mode. 
![landscape mode](https://user-images.githubusercontent.com/45735850/71550959-ecf65580-29a9-11ea-8ec6-0b57487037a5.jpg)
 
I tried to fix it myself but I'm not good at mobile CSS and I won't have a good way of testing it on mobile until mid-January. @violetcraze

**Comment by Fraasi** [comment]
If you take out the height of the nav, you can see the 'cut off' links again.

<img width="695" alt="2019-12-30_13-39-59" src="https://user-images.githubusercontent.com/22402899/71580664-41b0e200-2b0a-11ea-9ed3-e0aca4609e13.png">

**Comment by GypsyDangerous** [comment]
fixed by #2027
