### ISSUE TITLE
New store!

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#2062]
The store from #796 is no more and I worked with standard.tv to launch a new store with a small selection of high quality items (more potentially to be added over time). The url is:

https://standard.tv/thecodingtrain

It is soft launched right now but we can add it to the site whenever!

![Screen Shot 2020-01-17 at 9 14 44 AM](https://user-images.githubusercontent.com/191758/72618764-d50b5500-3909-11ea-8330-79e5b3ef765a.png)

**Comment by gruselhaus** [comment]
@shiffman how about this?

<img width="1792" alt="Bildschirmfoto 2020-01-18 um 02 46 44" src="https://user-images.githubusercontent.com/33380107/72656614-cd48c080-399c-11ea-9d23-55dde8abe30d.png">
<img width="1792" alt="Bildschirmfoto 2020-01-18 um 02 46 40" src="https://user-images.githubusercontent.com/33380107/72656615-cfab1a80-399c-11ea-8222-795dfd5817cd.png">

**Comment by shiffman** [comment]
This is great! Maybe let's try the enamel pin or the mugs as the image since the notebook looks similar to the books to the right?

**Comment by gruselhaus** [comment]
@shiffman 
<img width="2160" alt="Bildschirmfoto 2020-01-18 um 15 55 13" src="https://user-images.githubusercontent.com/33380107/72665672-ebe5a080-3a0a-11ea-9e83-a3b5a3023ea7.png">
<img width="2160" alt="Bildschirmfoto 2020-01-18 um 15 55 09" src="https://user-images.githubusercontent.com/33380107/72665674-ed16cd80-3a0a-11ea-9109-57d0992ac20f.png">

**Comment by shiffman** [comment]
Looks great!

**Comment by gruselhaus** [comment]
Merged 9891b5db2f368debb9520aa1dd666079ead20701
