### ISSUE TITLE
Coding in the cabana episode 3 optimisation

### ISSUE THREAD

**Issue by bundgaard** [CodingTrain/website#2107]
To optimise this further we should have a global index = 1, as we aren't interested in running from 1 to N, you are each time adding a bulk of 50 new entries to read and counter will go up till it reaches the `this.path.length`

The for-loop will go from 1 to 50, 1 to 100, 1 to 150, 1 to 200, ... 

Just a nice tips.
```

for (; this.idx < this.counter; this.idx++) { // counter er hurtig i starten efter i < 0, 64, 128, 196, 256, 

            let h = map(this.idx, 0, this.path.length, 0, 360)
            this.ctx.strokeStyle = `hsl(${h},100%, 50%)`
            this.drawLine(this.path[this.idx].a, this.path[this.idx].b, this.path[this.idx - 1].a, this.path[this.idx - 1].b);
        }
```

Doing all of your coding in vanilla javascript, really nice to compare the functionality between P5.js and vanilla

https://github.com/CodingTrain/website/blob/609baaf32bfcadd34558e7e9c5d6b511081929b7/CodingInTheCabana/Cabana_003_Hilbert_Curve/P5/sketch.js#L39

**Comment by KobeLiesenborgs** [comment]
Hi Bundgaard!

The algorithm can definitely be improved and changed for actual use, for the website however we tend to stick to the examples from the videos! Your points is valid for sure though!

Sorry for the slow reply, we didn't really use the issues system on here recently.

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!

Hope to see you there!
