### ISSUE TITLE
CNN video pages not working

### ISSUE THREAD

**Issue by GypsyDangerous** [CodingTrain/website#2143]
when you try to go to the page on the website for the cnn videos it throws a 404

**Comment by shiffman** [comment]
can you be more specific, where is the broken link? They are working from this page for me:

https://thecodingtrain.com/learning/ml5/

**Comment by GypsyDangerous** [comment]
The link in the description of the youtube videos

**Comment by GypsyDangerous** [comment]
https://thecodingtrain.com/Courses/ml5-beginners-guide/8.2-cnn-2.html

**Comment by GypsyDangerous** [comment]
it seems like the website is working fine, just the link in the video descriptions are wrong

**Comment by shiffman** [comment]
Fixed!
