### ISSUE TITLE
Message is not recieved in conents.js from background.js

### ISSUE THREAD

**Issue by thoughtlessmind** [CodingTrain/website#2307]
hey! I was learning to build chrome extensions. In part 11.5 video, there is a functionality where a message is passed from background.js to content.js and then log that message, but that is not working. I tried even pasting the same code as in the respective repo but still not working. 
Repo link:- https://github.com/CodingTrain/website/tree/master/Courses/programming_with_text/session11/11-04_Chrome_Extensions_Background_Scripts

Video link: -https://www.youtube.com/watch?v=ew9ut7ixIlI

**Comment by ngorden** [comment]
I pulled the repository fresh today and nothing seems broken...

Can you post steps to re-create the error?

**Comment by KobeLiesenborgs** [comment]
Hey everyone!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

P.S. Sorry for the late reply, we didn't use the issue section of this repository for a long while.

Hope to see you there!
