### ISSUE TITLE
Code files cannot be downloaded from The Coding Train website. More details below.

### ISSUE THREAD

**Issue by samyakbambole** [CodingTrain/website#2358]
When I want to download some code from the Coding Train Website, the browser takes me to https://minhaskamal.github.io/DownGit/ And when I try to download the .zip file in my Chrome browser, Chrome blocks the file saying that "This file is dangerous so chrome has blocked it." 

I hope this issue gets resolved soon.

**Comment by gruselhaus** [comment]
duplicate of #2178
