### ISSUE TITLE
Question about Pool Selection (9.8 Nature of Code)

### ISSUE THREAD

**Issue by Vikram-Bhat** [CodingTrain/website#2374]
Sorry, I haven't used GitHub a lot, so this might be the wrong place, but I had a question about the pool selection algorithm in [9.8: Genetic Algorithm: Improved Pool Selection - The Nature of Code](https://www.youtube.com/watch?v=ETphJASzYes). I understand the basic concept, but wouldn't this give preference to earlier items in the list? It doesn't really matter with what I am doing (I'm just playing around with genetic algorithms), but I was just wondering.

**Comment by violetcraze** [comment]
I'm not entirely sure but you might have better luck asking on The Coding Train's discord. Here's a link to that: https://discord.gg/hPuGy2g
