### ISSUE TITLE
'ml5 ' is not defined

### ISSUE THREAD

**Issue by dhruvrawat101** [CodingTrain/website#2378]
I am trying to run the code but it can't detect ml5 object. Version I am using = 0.4.3
Here are some snippets of the code
Code is from teachable machine series 

![p5_editor error](https://user-images.githubusercontent.com/51899618/84810087-7537e800-b028-11ea-8394-867598761cc1.PNG)
![p5 index error](https://user-images.githubusercontent.com/51899618/84810283-c3e58200-b028-11ea-9aa1-1869401611ee.PNG)

**Comment by violetcraze** [comment]
@dhruvrawat101 I was unable to reproduce this bug. Looks like the [example in the web editor](https://editor.p5js.org/codingtrain/sketches/tqoOkW_ai) from part two of teachable machine is working fine. Could you elaborate on your problem and/or include a link?

**Comment by chiape** [comment]
Me either and I hope I am not too late for that but you can try to use the latest version, according to the documentation: 
   
v0.6.0

<script src="https://unpkg.com/ml5@0.6.0/dist/ml5.min.js" **type="text/javascript"**></script>

If you need to use an earlier version for any reason, you can change the version number. You can use those previous versions by replacing <version> with the ml5 version of interest:

<script src="https://unpkg.com/ml5@<version>/dist/ml5.min.js" type="text/javascript"></script>

**Comment by KobeLiesenborgs** [comment]
Hey everyone!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

Hope to see you there!
