### ISSUE TITLE
Installation guide missing

### ISSUE THREAD

**Issue by Ashikpaul** [CodingTrain/website#2412]
I was going through the website and thought of adding a feature. But I didn't find a installation guide on running this site locally. 

It would be great if an installation guide is provided in the README section.

Thank you😍

**Comment by violetcraze** [comment]
We have the core contribution guide: https://thecodingtrain.com/Guides/core-contribution-guide.html

But thanks for bringing this up because I think it needs a few minor updates and it would be good to make it easier to find from the readme.

**Comment by Ashikpaul** [comment]
Oh Sorry! I should have checked all files.
Yes, it would be great if this was accessible from README file.

Thank you 😍 @violetcraze for your response.
