### ISSUE TITLE
Hacktoberfest - Make Something 💖 and Share A Link on The Coding Train Website

### ISSUE THREAD

**Issue by violetcraze** [CodingTrain/website#2615]
Hello hackers!

All aboard The Coding Train 🚂🌈💖! The Coding Train is an educational YouTube channel where Dan Shiffman teaches JavaScript and Java with [p5.js](https://p5js.org/) and [Processing](https://processing.org/).

A great way to contribute is by sharing a project you make based on one of the coding challenge videos on the Coding Train YouTube channel. Here's a couple simple steps to tell you how:

1. **Choose and watch a Coding Challenge.** You can see all the coding challenges on our website: https://thecodingtrain.com/CodingChallenges/. Below are a couple of favorites that people enjoy remixing.
> - Tic Tac Toe: https://thecodingtrain.com/CodingChallenges/149-tic-tac-toe.html
> - 10Print in p5.js: https://thecodingtrain.com/CodingChallenges/076-10print.html
> - Minesweeper: https://thecodingtrain.com/CodingChallenges/071-minesweeper.html

2. **Make something!!** Make something cool based on the coding challenge. An in browser code editor is the [p5.js web editor](https://editor.p5js.org/) (no install required). Just hit `View Code` or `Web Editor` on the coding challenge webpage to see the code from the video if you don't want to start from scratch.

3. **Add a link to your creation to the site with a pull request.** We have a whole guide on doing this which can be found here: https://thecodingtrain.com/Guides/community-contribution-guide. There's also a video of Dan showing how it's done: https://youtu.be/fkIr0inoQ7Y.

Thanks for checking out The Coding Train. We hope you stay awhile and enjoy making fun projects!

If you've got any questions about the process feel free to ask them below. And if you want help coding or debugging check out our discord server: https://discord.gg/hPuGy2g.

Side note, please do **not** say that your pull request closes this issue. It will be closed at the end of the month.

Please follow our code of conduct: https://github.com/CodingTrain/Code-of-Conduct

**Comment by thinkswell** [comment]
@violetcraze, Hello, I have made an amazing version of flappy bird it's my first contribution to coding train, can you please review it, PR #2654 
Thank You.

**Comment by galElmalah** [comment]
Hey, do we need to mention the PR here or just opening one is enough?
just in case 😄 
https://github.com/CodingTrain/website/pull/2701

**Comment by JacobGeoGeek** [comment]
Question: can we build a different version (or another subject/theme) of a coding challenge? 

For example, I would like to redo the [visualizing challenge](https://thecodingtrain.com/CodingChallenges/109-subscribers-map.html), but with a different set of data (instead of displaying the subscribers) ?

Also, can we choose our own programming language (or we have to use p5.js) ?

cheer and Happy Hackoctoberfest 2020

**Comment by Ashikpaul** [comment]
@JacobGeoGeek, Yes you can submit your own version. It can be with any set of data. 
Please take a look at the contribution which was already made.

https://www.rand-on.com/projects/2018_tax_evasion/tax_evasion.html

![image](https://user-images.githubusercontent.com/17526871/96619989-72296d00-1324-11eb-862d-bf103ba1eec8.png)

**Comment by violetcraze** [comment]
Thanks to everyone who participated in Hacktoberfest!

**Comment by b-yogesh** [comment]
Hello @violetcraze , I had participated in Hacktoberfest 2020, and my 2 PRs were supposed to mature today and 1 PR tomorrow, but since you closed this issue, now it shows that this is Ineligible repository. Can this be fixed somehow? Thank you.

**Comment by JacobGeoGeek** [comment]
I also have the same problem

**Comment by violetcraze** [comment]
@b-yogesh @JacobGeoGeek So sorry about that. I was cleaning up and removed the label from the repository. Just added it again. Please let me know if that fixed it. If not, I was told over on #2762 that I can label specific pull request to be accepted and I'll go back and add that label.

**Comment by JacobGeoGeek** [comment]
Hello @violetcraze, 

what do you mean by "Just added it again".
not sure if that Can help you but here's my two PRs: #2821 and #2815 

Cheers

**Comment by decrecementofeliz** [comment]
Hi @violetcraze I had the same problem, my PR is shown as Ineligible
#2839 
Can you have a look? thanks

**Comment by b-yogesh** [comment]
Hi @violetcraze, thanks for replying. No, it has not fixed my problem yet. :( #2758, #2759 and #2772 are all ineligible now.

**Comment by violetcraze** [comment]
@JacobGeoGeek @decrecementofeliz @b-yogesh 
I'm going back and adding hacktoberfest-accepted labels to all the pull request that might have been effected in the hope fixes things, but I think even if that's working it won't fix pull requests that matured in the last 24 hours or so. I'm also waiting to hear back from hacktoberfest support to make sure all the pull requests are counted. If this all plays out and you end up not meeting the requirements because of hacktoberfest label being removed from the repository I'll send you some Coding Train merch or donate to have a tree planted.

**Comment by JacobGeoGeek** [comment]
@violetcraze thanks for the support

**Comment by b-yogesh** [comment]
@violetcraze thank you. :)

**Comment by violetcraze** [comment]
Update:
I got a message back from hacktoberfest support here's what it said.

>Our team are aware of this issue and are looking into a possible solution for it.
>
>However, at present, this is the intended behaviour of Hacktoberfest. If a maintainer removes the topic or un-accepts a PR during the review period, that PR will become invalid. As Hacktoberfest has now ended, even if the maintainer re-accepts the PR or adds the topic back, the PR can no longer start the review period again, so will be stuck as invalid.

Sounds like they're working on a solution and I'll follow up in 3 days to see where things are at if I don't hear back by then.

**Comment by decrecementofeliz** [comment]
thank you @violetcraze

**Comment by Ivan-Denisovich-py** [comment]
@violetcraze You are very kind. I've had the same problem too, although I didn't mention this issue in any of my pull requests, so basically it's my fault. But if you get any news let us know. Thanks for being so kind to care! Cheers!

**Comment by violetcraze** [comment]
Update:
Haven't heard back from the Hacktoberfest team yet so I send a follow up email asking for more details and if they intend on releasing a solution and if so when. I'll follow up one more time if I don't hear back by Tuesday next week.

**Comment by JacobGeoGeek** [comment]
thanks for the update

**Comment by violetcraze** [comment]
Update:
Got this message back from Hacktoberfest.

>Our team are aware of this issue and are looking into a possible solution for it, however, at present, we cannot provide any updates.

I'll follow up next Monday if I don't hear anything by then.

**Comment by violetcraze** [comment]
Sorry for the delayed update. Have emailed Hacktoberfest again asking for more definite time frame for a solution or if they intend on fixing this issue at all. I apologies that this process is taking so long. I'll post an update when I get a response it normally takes a day or two.
