### ISSUE TITLE
Have all Coding Challenges in Processing & p5 

### ISSUE THREAD

**Issue by meiamsome** [CodingTrain/website#267]
List of challenges:

- [x] Coding Challenge 1: Starfield in Processing
- [x] Coding Challenge 2: Menger Sponge Fractal
- [x] Coding Challenge 3: The Snake Game
- [x] Coding Challenge 4: Purple Rain in Processing
- [x] Coding Challenge 5: Space Invaders
- [x] Coding Challenge 6: Mitosis Simulation
- [x] Coding Challenge 7: Solar System in Processing - Part 1 (2D)
- [ ] Coding Challenge 8: Solar System in Processing - Part 2 (3D)
- [ ] Coding Challenge 9: Solar System in Processing - Part 3 (3D textures)
- [x] Coding Challenge 10: Maze Generator
- [x] Coding Challenge 11: 3D Terrain Generation with Perlin Noise in Processing
- [x] Coding Challenge 12: The Lorenz Attractor
- [x] Coding Challenge 13: Reaction Diffusion Algorithm in p5.js
- [x] Coding Challenge 14: Fractal Trees - Recursive
- [x] Coding Challenge 15: Fractal Trees - Object Oriented
- [x] Coding Challenge 16: Fractal Trees - L-System
- [x] Coding Challenge 17: Fractal Trees - Space Colonization
- [ ] Coding Challenge 18: 3D Fractal Trees
- [x] Coding Challenge 19: Superellipse
- [ ] Coding Challenge 20: 3D Cloth with toxiclibs
- [x] Coding Challenge 21: Mandelbrot Set
- [ ] Coding Challenge 22: Julia Set
- [x] Coding Challenge 23: 2D Supershapes
- [x] Coding Challenge 24: Perlin Noise Flow Field
- [ ] Coding Challenge 25: Spherical Geometry
- [ ] Coding Challenge 26: 3D Supershapes
- [x] Coding Challenge 27: Fireworks!
- [x] Coding Challenge 28: Metaballs
- [x] Coding Challenge 29: Smart Rockets
- [x] Coding Challenge 30: Phyllotaxis
- [x] Coding Challenge 31: Flappy Bird
- [ ] Coding Challenge 32: Agar.io:
- - [x] Part 1
- - [ ] Part 2 (Websocket)
- [x] Coding Challenge 33: Poisson-disc Sampling
- [x] Coding Challenge 34: Diffusion-Limited Aggregation
- [x] Coding Challenge 35: Traveling Salesperson:
- - [x] Part 1
- - [x] Part 2
- - [x] Part 3
- - [x] Part 4
- [x] Coding Challenge 36: Blobby!
- [ ] Coding Challenge 37: Diastic Machine
- [ ] Coding Challenge 38: Word Interactor
- [ ] Coding Challenge 39: Mad Libs Generator
- [x] Coding Challenge 40: Word Counter in JavaScript
- [ ] Coding Challenge 41: Clappy Bird!
- [ ] Coding Challenge 42: Markov Chains
- [ ] Coding Challenge 43: Context-Free Grammar
- [ ] Coding Challenge 44: AFINN-111 Sentiment Analysis
- [ ] Coding Challenge 45: Saving p5.js Drawings to Firebase
- [x] Coding Challenge 46: Asteroids
- [x] Coding Challenge 47: Pixel Sorting in Processing
- [x] Coding Challenge 48: White House Social Media Data Visualization
- [ ] Coding Challenge 49: Photo Mosaic with White House Social Media Images
- [x] Coding Challenge 50: Animated Circle Packing:
- - [x] Part 1
- - [x] Part 2
- [x] Coding Challenge 51: A\* Pathfinding Algorithm
- [x] Coding Challenge 52: Random Walker
- [x] Coding Challenge 53: Random Walker with Vectors and Lévy Flight
- [ ] Coding Challenge 54: Islamic Star Patterns:
- - [x] Part 1
- - [ ] Part 2
- [x] Coding Challenge 55: Mathematical Rose Patterns
- [x] Coding Challenge 56: Attraction and Repulsion Forces
- [x] Coding Challenge 57: Mapping Earthquake Data
- [ ] Coding Challenge 58: 3D Earthquake Data Visualization
- [ ] Coding Challenge 59: Steering Behaviors
- [x] Coding Challenge 60: Butterfly Generator
- [x] Coding Challenge 61: Fractal Spirograph
- [ ] Coding Challenge 62: Plinko with Matter.js
- [ ] Coding Challenge 63: Texturing Cloth Simulation
- [ ] Coding Challenge 64: Kinematics:
- - [x] Part 1A
- - [ ] Part 1B
- - [x] Part 2
- - [x] Part 3
- - [x] Part 4
- [x] Coding Challenge 65: Binary Search Tree
- - [x] Part 1 
- - [x] Part 2 (Visualization)
- [ ] Coding Challenge 66: JavaScript Countdown Timer
- [x] Coding Challenge 67: Pong!
- [ ] Coding Challenge 68: Breadth-First Search
- [x] Coding Challenge 69: Evolutionary Steering Behaviors
- [ ] Coding Challenge 70: Nearest Neighbors Recommendation Engine
- [x] Coding Challenge 71: Minesweeper
- [ ] Coding Challenge 72: Frogger
- [ ] Coding Challenge 73: Acrostic
- [x] Coding Challenge 74: Clock
- [ ] Coding Challenge 75: Wikipedia
- [x] Coding Challenge 76: 10PRINT
- [x] Coding Challenge 77: Recursion
- [x] Coding Challenge 78: Simple Particle System
- [ ] Coding Challenge 79: Number Guessing Chatbot
- [ ] Coding Challenge 80: Voice Chatbot with p5.Speech (Can this even be converted?)
- [x] Coding Challenge 81: Circle Morphing:
- - [x] Part 1
- - [x] Part 2
- [x] Coding Challenge 82: Image Chrome Extension (No Processing Equivalent)
- [x] Coding Challenge 83: Chrome Extension with p5js (No Processing Equivalent)
- [x] Coding Challenge 84: Word Definition Extension (No Processing Equivalent)
- [x] Coding Challenge 85: The Game of Life
- [x] Coding Challenge 86: Bees and Bombs
- [x] Coding Challenge 87: 3D Knots
- [x] Coding Challenge 88: Snowfall
- [x] Coding Challenge 89: Langton's ant
- [x] Coding Challenge 90: Dithering
- [x] Coding Challenge 91: Snakes & Ladders
- [x] Coding Challenge 92: XOR
- [x] Coding Challenge 93: Double Pendulum
- [x] Coding Challenge 94: 2048
- [x] Coding Challenge 95: Approximating Pi
- [x] Coding Challenge 96: Visualizing the Digits of Pi
- [ ] Coding Challenge 97: The Book of Pi:
- - [ ] Part 1
- - [ ] Part 2
- [x] Coding Challenge 98: QuadTree:
- - [x] Part 1
- - [x] Part 3 (Collisions)
- [ ] Coding Challenge 99: Color Predictor
- [ ] Coding Challenge 100: Neuro Evolution Flappy Bird:
- - [ ] Part 1
- - [ ] Part 5
- [ ] Coding Challenge 101: May the 4th
- [ ] Coding Challenge 102: Water Ripples
- [ ] Coding Challenge 103: Flames
- [ ] Coding Challenge 104: Linear Regression with tensorflow.js
- [ ] Coding Challenge 105: Polynomial Regression with tensorflow.js
- [ ] Coding Challenge 106: The XOR Problem with tensorflow.js
- [x] Coding Challenge 107: Sandpiles
- [x] Coding Challenge 108: Barnsley Fern
- [ ] Coding Challenge 109: Subscriber Map
- [ ] Coding Challenge 110: Recaman:
- - [x] Part 1
- - [ ] Part 2 (Music)
- [x] Coding Challenge 111: Animated Sprites
- [x] Coding Challenge 112: 3D Rendering
- [x] Coding Challenge 113: Hypercube
- [x] Coding Challenge 114: Bubble Sort Visualization
- [x] Coding Challenge 115: Snake Game Redux
- [x] Coding Challenge 116: Lissajous
- [x] Coding Challenge 117: Seven Segment Display
- [ ] Coding Challenge 118: Mastodon Tree Bot (Node.js Version)
- [x] Coding Challenge 119: Binary to Decimal Conversion
- [x] Coding Challenge 120: Bit Shifting
- [x] Coding Challenge 121: Logo:
- - [x] Part 1
- - [x] Part 2
- [ ] Coding Challenge 122: Quick Draw:
- - [ ] Part 1
- - [ ] Part 2
- [x] Coding Challenge 123: Chaos Game:
- - [x] Part 1
- - [x] Part 2
- [x] Coding Challenge 124: Flocking Boids
- [x] Coding Challenge 125: Fourier Series
- [x] Coding Challenge 126: Toothpicks
- [x] Coding Challenge 127: Snowflake
- [ ] Coding Challenge 128: Snowflakes with SketchRNN
- [x] Coding Challenge 129: Koch Snowflake
- [ ] Coding Challenge 130: 
- - [x] Part 1: Drawing with Fourier Transform and Epicycles
- - [ ] Part 2: Fourier Transform User Drawing
- - [x] Part 3: Fourier Transform Drawing with Complex Number Input
- [x] Coding Challenge 131: Bouncing DVD Logo
- [ ] Coding Challenge 132: Fluid Simulation
- [x] Coding Challenge 133: Times Tables Cardioid Visualization
- [x] Coding Challenge 134: Heart Curve
- - [x] Part 1
- - [x] Part 2
- [x] Coding Challenge 135: GIF Loop
- [x] Coding Challenge 136: 
- - [x] Part 1 Polar Perlin Noise Loops
- - [x] Part 2 Perlin Noise GIF Loops
- [x] Coding Challenge 137: 4D OpenSimplex Noise Loop
- [ ] Coding Challenge 138: Angry Birds with Matter.js
- [ ] Coding Challenge 139: Calculating Digits of Pi with Collisions
- [ ] Coding Challenge 140: Leibniz Formula for Pi
- [ ] Coding Challenge 141: Calculating Digits of Pi with Mandelbrot Set
- [ ] Coding Challenge 142: Rubik's Cube 
- - [ ] Part 1
- - [ ] Part 2
- - [ ] Part 3
- [ ] Coding Challenge 143: Quicksort
- [x] Coding Challenge 144: 2D Black Hole Visualization
- [ ] Coding Challenge 145: Ray Casting 2D
- [ ] Coding Challenge 146: Rendering Ray Casting

**Comment by Merijn-DH** [comment]
CC 76 (10PRINT) was ported in commit 9abda5d

**Comment by Merijn-DH** [comment]
Commit 34f8f99 renumbered some Coding Challenges. To summarize:
- CC 72 became Frogger
- CC 73 became Acrostic

**Comment by TheLastDestroyer** [comment]
There might be a few of these, should I create a pull request for each CC or lump them all in one?

**Comment by TheLastDestroyer** [comment]
also https://github.com/akraus53/SmartRockets exists for number 29

**Comment by shiffman** [comment]
Thank you for the contributions @TheLastDestroyer, I think separate pull requests is good!

**Comment by TheLastDestroyer** [comment]
That should be the changes done, I wasn't entirely sure how do deal with attribution in the header, can you take a look and if you're not happy I can change it.

**Comment by gruselhaus** [comment]
@meiamsome Is the list still up to date?

And can you please tick the CC36? (See #794)

Thanks a lot 😃

**Comment by gruselhaus** [comment]
@shiffman Does it make sense to pin this issue so we can keep an eye on it?

**Comment by shiffman** [comment]
@gruselhaus yes! didn't realize this was a feature, just tried it.

**Comment by shiffman** [comment]
In theory all the challenges should also have a web editor link, I'll message you in slack about this.

**Comment by anuraghazra** [comment]
Did anyone tried this?
http://faculty.purchase.edu/joseph.mckay/p5jsconverter.html

**Comment by GypsyDangerous** [comment]
@meiamsome I have a port of the Fourier transform challenge

**Comment by GypsyDangerous** [comment]
@shiffman

**Comment by gruselhaus** [comment]
Continued in #1347
