### ISSUE TITLE
Link for `Bug in High Contrast and Dark Mode p5.js-web-editor` issue

### ISSUE THREAD

**Issue by samyakbambole** [CodingTrain/website#2760]
https://github.com/processing/p5.js-web-editor/issues/1642

**Comment by samyakbambole** [comment]
This Was Reported by @CodingTrain in a stream.

**Comment by catarak** [comment]
This has been fixed by https://github.com/processing/p5.js-web-editor/pull/1645.

**Comment by samyakbambole** [comment]
> This has been fixed by [processing/p5.js-web-editor#1645](https://github.com/processing/p5.js-web-editor/pull/1645).

I Know but I wanted to create this issue for informing @shiffman

**Comment by samyakbambole** [comment]
I Created the issue in https://github.com/processing/p5.js-web-editor and @SundeepChand Fixed the Bug.

**Comment by violetcraze** [comment]
@samyakbambole Thanks so much for reporting this to the web editor. Great to hear it was fixed!! Dan will have gotten an email when you tagged him so he'll probably see this at some point. I'm closing this issue because it's been resolved but can still be viewed just not active.

**Comment by shiffman** [comment]
woohoo thank you @samyakbambole!

**Comment by samyakbambole** [comment]
> woohoo thank you @samyakbambole!

You're Welcome, Sir!
