### ISSUE TITLE
Add Missing Pages in Programing with Text Series 💫

### ISSUE THREAD

**Issue by violetcraze** [CodingTrain/website#2762]
A lot of the Programming with Text videos are missing pages we could you're help adding these pages. 🌠

If you'd like to work on adding a page. Here's the steps.

1. 🌼 **Choose a video from the list and comment to claim it.** Below there's a list of videos that need pages to be created. Comment on this issue to claim one so people aren't working on the same one. *Be sure to check and see if there's recent comments because checkboxes on the list might not be entirely up to date.*

> - *Note: Only take on 1-3 videos at a time, but feel free take on more after you've submitted a pull request.*

2. 🌺 **Follow the [Pages Contribution Guide](https://thecodingtrain.com/Guides/pages-contribution-guide.html) to add a page for the video.** In this case the pages should go under `_learning/programing-with-text` and any code should go in `learning/programing-with-text`. If you're confused about any of the steps in the guide feel free to comment with questions on this issue.

> - Code maybe located: https://github.com/shiffman/A2Z-F16 or https://github.com/CodingTrain/website/tree/main/Courses/programming_with_text
> - Pages Contribution Guide Link: https://thecodingtrain.com/Guides/pages-contribution-guide.html

3. 🌸 **Make a pull request with the new page!!**

> - *Note: Please don't say your pull request closes this issue. I'll close it when all the pages are done.*

**List of Programing with Text Videos**

|Claimed|Done|Number|Link|
|-|-|-|-|
||<ul><li> - [X] </li></ul>| 1.1 | https://youtu.be/HRANU6KtNEs |
||<ul><li> - [X] </li></ul>| 1.2 | https://youtu.be/d3OcFexe9Ik |
||<ul><li> - [X] </li></ul>| 1.3 | https://youtu.be/uNQSVU0IKec |
||<ul><li> - [X] </li></ul>| 1.4 | https://youtu.be/0Mq2CxspF5s |
||<ul><li> - [X] </li></ul>| 1.5 | https://youtu.be/DcoAjEZYies |
||<ul><li> - [X] </li></ul>| 1.6 | https://youtu.be/YTzVbuV89RE |
||<ul><li> - [X] </li></ul>| 2.1 | https://youtu.be/7DG3kCDx53c |
||<ul><li> - [X] </li></ul>| 2.2 | https://youtu.be/YTocEnDsMNw |
||<ul><li> - [X] </li></ul>| 2.3 | https://youtu.be/EfJU0Y9WAZ4 |
||<ul><li> - [X] </li></ul>| 2.4 | https://youtu.be/c9HbsUSWilw |
||<ul><li> - [X] </li></ul>| 2.5 | https://youtu.be/Z66TeSTcP-Q |
||<ul><li> - [X] </li></ul>| 2.6 | https://youtu.be/W7S_Vmq0GSs |
||<ul><li> - [X] </li></ul>| 2.7 | https://youtu.be/t029QcVHtas |
||<ul><li> - [X] </li></ul>| 2.8 | https://youtu.be/fdyqutmcI2Q |
||<ul><li> - [X] </li></ul>| 2.9 | https://youtu.be/7a-a6lKoyIQ |
||<ul><li> - [X] </li></ul>| 2.10 | https://youtu.be/pMn44yFxGWk |
||<ul><li> - [X] </li></ul>| 3.1 | https://youtu.be/lIPEvh8HbGQ |
||<ul><li> - [X] </li></ul>| 3.2 | https://youtu.be/tk_JGu2AbJY |
||<ul><li> - [X] </li></ul>| 3.3 | https://youtu.be/XUhyfkE4BS8 |
||<ul><li> - [X] </li></ul>| 5.1 | https://youtu.be/tE-ZYXU8A8U |
||<ul><li> - [X] </li></ul>| 5.2 | https://youtu.be/_5jdE6RKxVk |
||<ul><li> - [X] </li></ul>| 5.3 | https://youtu.be/6DoJob85jE0 |
||<ul><li> - [X] </li></ul>| 6.1 | https://youtu.be/v4kL0OHuxXs |
||<ul><li> - [X] </li></ul>| 6.2 | https://youtu.be/aq9Wf7F5e84 |
||<ul><li> - [X] </li></ul>| 7.1 | https://youtu.be/Rhqk9HYiB7Q |
||<ul><li> - [X] </li></ul>| 7.2 | https://youtu.be/C3EwsSNJeOE |
||<ul><li> - [X] </li></ul>| 7.3 | https://youtu.be/VaAoIaZ3YKs |
||<ul><li> - [X] </li></ul>| 7.4 | https://youtu.be/UzVtOS2DBA8 |
||<ul><li> - [X] </li></ul>| 8.1 | https://youtu.be/P-Upi9TMrBk |
||<ul><li> - [X] </li></ul>| 8.2 | https://youtu.be/6oiabY1xpBo |
||<ul><li> - [X] </li></ul>| 8.3 | https://youtu.be/e4qKBkwwkNg |
||<ul><li> - [X] </li></ul>| 8.4 | https://youtu.be/oMhAd864bBc |
||<ul><li> - [X] </li></ul>| 8.5 | https://youtu.be/6iZiqQZBQJY |
||<ul><li> - [X] </li></ul>| 8.6 | https://youtu.be/4zr8j-jeU_M |
||<ul><li> - [X] </li></ul>| 8.7 | https://youtu.be/GZ2nwxhQUTU |
||<ul><li> - [X] </li></ul>| 9.1 | https://youtu.be/JrHT1iqSrAQ |
||<ul><li> - [X] </li></ul>| 9.2 | https://youtu.be/7lEU1UEw3YI |
||<ul><li> - [X] </li></ul>| 9.3 | https://youtu.be/NcewaPfFR6Y |
||<ul><li> - [X] </li></ul>| 10.1 | https://youtu.be/slmSCEho31g |
||<ul><li> - [X] </li></ul>| 10.2 | https://youtu.be/wf8w1BJb9Xc |
||<ul><li> - [X] </li></ul>| 10.3 | https://youtu.be/v0CHV33wDsI |
||<ul><li> - [X] </li></ul>| 10.4 | https://youtu.be/q_bXBcmfTJM |
||<ul><li> - [X] </li></ul>| 11.1 | https://youtu.be/hkOTAmmuv_4 |
||<ul><li> - [X] </li></ul>| 11.2 | https://youtu.be/DloHqUfPbJc |
||<ul><li> - [X] </li></ul>| 11.3 | https://youtu.be/9Tl3OmwrSaM |
||<ul><li> - [X] </li></ul>| 11.4 | https://youtu.be/ew9ut7ixIlI |
||<ul><li> - [X] </li></ul>| 11.5 | https://youtu.be/YQnRSa8MGwM |
||<ul><li> - [X] </li></ul>| 11.6 | https://youtu.be/kP-UmHrxCYk |
||<ul><li> - [X] </li></ul>| 11.7 | https://youtu.be/vNb3P5KIxXw |
||<ul><li> - [X] </li></ul>| 11.8 | https://youtu.be/RJtjp-Vtwjs |

**Comment by vr1e** [comment]
I can help with getting these videos listed. Let me do 1.3 for warmup :)

**Comment by IngridGdesigns** [comment]
Hi, I can work on 1.4 and 1.5, please :)

**Comment by vr1e** [comment]
@violetcraze Maybe you can re-distribute some remaining ones to us that are interested since I see some people are already working on some of the other ones. 🎁👀

**Comment by Ashikpaul** [comment]
I have already submitted a PR for 1.3 and 1.4

**Comment by violetcraze** [comment]
@vr1e @IngridGdesigns Sorry about the confusion looks like it might be poor wording on my part. @Ashikpaul did create new issues claiming those ones earlier. @vr1e How about you work on 3.1? @IngridGdesigns do you want to work on do you want to work on 5.1?

@Ashikpaul If you want to work on more, it's fine if you want to open a separate issue, but could you also comment here so people don't have to look in other places to see what's available.

**Comment by Ashikpaul** [comment]
@violetcraze sure will do. Thanks😃

**Comment by IngridGdesigns** [comment]
@violetcraze,  I can work on 5.1

**Comment by vr1e** [comment]
@violetcraze Sign me up to finish those starting with 3 and maybe the ones from 7 to 9. My OCD is kicking in 🔥

**Comment by gmgalvan** [comment]
@violetcraze can I take 5.2?

**Comment by violetcraze** [comment]
@gmgalvan done

@vr1e updated the list to show you'd be working on section 8. Let me know if you're ready to be done. I don't want to make you feel like you have to work on it.

**Comment by hootio** [comment]
I can do 6.1 & 6.2!

**Comment by aanchal-adk** [comment]
I can do 1.5

**Comment by aanchal-adk** [comment]
I'll can work on 1.6 and 5.3 that are remaining.

**Comment by violetcraze** [comment]
@IngridGdesigns Are you still planning to work on 5.1? If so, could you do it sometime in the next week? Love to finish up this issue. If you changed your mind and don't want to work on it that's fine too just let me know.

@KobeLiesenborgs Was planning to work on 9.1 - 9.3 myself but if you'd like to do them so you can practice adding pages. Let me know.

**Comment by aanchal-adk** [comment]
@violetcraze Could you please add the label `hacktoberfest-accepted` these closed PRs? These PRs became invalid for the hacktoberfest after the `hacktoberfest` label was removed from the repository.
https://github.com/CodingTrain/website/pull/2803
https://github.com/CodingTrain/website/pull/2801
https://github.com/CodingTrain/website/pull/2793

**Comment by Ashikpaul** [comment]
> @violetcraze Could you please add the label `hacktoberfest-accepted` these closed PRs? These PRs became invalid for the hacktoberfest after the `hacktoberfest` label was removed from the repository.
> #2803
> #2801
> #2793

True, Even my PRs weren't accepted. @violetcraze Please add the label
Thanks

**Comment by violetcraze** [comment]
@aanchal-adk @Ashikpaul Sorry about that I was cleaning up from hacktoberfest and removed the label. I added it back to repository, but if that didn't fix it let me know I'll go back and add the label to all the pull requests in the last two weeks.

**Comment by Ashikpaul** [comment]
> @aanchal-adk @Ashikpaul Sorry about that I was cleaning up from hacktoberfest and removed the label. I added it back to repository, but if that didn't fix it let me know I'll go back and add the label to all the pull requests in the last two weeks.

@violetcraze unfortunately that didn't fix the issue. It's ok. Will try next year. Thank you

**Comment by vr1e** [comment]
@violetcraze @Ashikpaul @aanchal-adk I think it's the topic part that is missing or "hacktoberfest-accepted" label to the PR.

![image](https://user-images.githubusercontent.com/17619481/98028714-c5b0b600-1e0e-11eb-99e4-993b60d9683e.png)

**Comment by violetcraze** [comment]
@Ashikpaul @vr1e I tried adding the hacktoberfest-accepted label to all of your pull requests from last month. Let me know if that worked and I'll go back and do everyone's. If not I'll contact hacktoberfest support to see if we can get them counted.

**Comment by violetcraze** [comment]
@aanchal-adk @Ashikpaul @vr1e 
Here's the update. I'm going back and adding hacktoberfest-accepted labels to all the pull request that might have been effected in the hope fixes things, but I think even if that's working it won't fix pull requests that matured in the last 24 hours or so. I'm also waiting to hear back from hacktoberfest support to make sure all the pull requests are counted. If this all plays out and you end up not meeting the requirements because of hacktoberfest label being removed from the repository I'll send you some Coding Train merch or donate to have a tree planted.

**Comment by violetcraze** [comment]
Update:
I got a message back from hacktoberfest support here's what it said.

>Our team are aware of this issue and are looking into a possible solution for it.
>
>However, at present, this is the intended behaviour of Hacktoberfest. If a maintainer removes the topic or un-accepts a PR during the review period, that PR will become invalid. As Hacktoberfest has now ended, even if the maintainer re-accepts the PR or adds the topic back, the PR can no longer start the review period again, so will be stuck as invalid.

Sounds like they're working on a solution and I'll follow up in 3 days to see where things are at if I don't hear back by then.

**Comment by aanchal-adk** [comment]
@violetcraze Thank you for the follow up. It's totally fine with me even if the issue doesn't get resolved. Thank you for your efforts.

**Comment by violetcraze** [comment]
Update:
Haven't heard back from the Hacktoberfest team yet so I send a follow up email asking for more details and if they intend on releasing a solution and if so when. I'll follow up one more time if I don't hear back by Tuesday next week.

**Comment by violetcraze** [comment]
Update:
Got this message back from Hacktoberfest.
>Our team are aware of this issue and are looking into a possible solution for it, however, at present, we cannot provide any updates.
I'll follow up next Monday if I don't hear anything by then.

**Comment by violetcraze** [comment]
Sorry for the delayed update. Have emailed Hacktoberfest again asking for more definite time frame for a solution or if they intend on fixing this issue at all. I apologies that this process is taking so long. I'll post an update when I get a response it normally takes a day or two.

**Comment by vr1e** [comment]
@violetcraze Thank you very much for all the effort! Digital Ocean handled the whole thing a bit clumsy and uncoordinated this year.
I had a lot of perso
nal stuff going on lately, hence my very late reply.
