### ISSUE TITLE
Broken link in 404 page

### ISSUE THREAD

**Issue by SibianDG** [CodingTrain/website#2829]
Broken link in the 404 page of the site. The 'Home' should be changed.

**Comment by jmannfeld** [comment]
I can work on this. What should it be changed to? "visit the Homepage"? Or I can change it to link to the `/CodingChallenges` page.

**Comment by SibianDG** [comment]
Well, that the question I've got about the link. So, it's a question to the maintainers. :)

**Comment by gruselhaus** [comment]
Why is the link 'broken'?

**Comment by SibianDG** [comment]
Ow, I didn't see the part in the URL: `{{ '/' | relative_url }}`. Sorry about that.
