### ISSUE TITLE
Allows Community Contributions on 404 page

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/website#2870]
![image](https://user-images.githubusercontent.com/59444569/98475289-bc16bc00-221b-11eb-8b82-51c6719c3319.png)
Community Contributions shown on 404 page

**Comment by violetcraze** [comment]
This is an intentional easter egg for people to share projects that might not have gone to plan. Says that in the description. Let me know if the wording is confusing and needs to be clarified.
