### ISSUE TITLE
Remove outlines

### ISSUE THREAD

**Issue by harshhhdev** [CodingTrain/website#2876]
![image](https://user-images.githubusercontent.com/69592270/99012944-71e45200-251d-11eb-800e-c67bd07cef65.png)

Right now, when you click on a button there is a weird outline on it. This may be intentional, but in my opinon it doesn't look that good and feels weird/out of place.

**Comment by violetcraze** [comment]
I believe this might be for accessibility. I'll have to look into it more. It'll do my best to do that in the next 3 days or so.

Also would like to hear @phucduong86's opinion.

If it turns out to not be important to accessibility I wouldn't be against removing it.

**Comment by harshhhdev** [comment]
A bit curious, not trying to bicker or anything.

How're these outlines helping accessibility? I usually have a tendency to take them out in my personal projects and I was wondering if I should stop doing that.

**Comment by calafm** [comment]
Hello! Since I didn't want to commit directly, I made a pull request on this. 

I removed the white-border from the span. Hope it's alright. :)

**Comment by phucduong86** [comment]
Hi,

Sorry I haven't had a chance to respond to this earlier.
It is required for accessibility so that user know it's the focused element.

**Comment by harshhhdev** [comment]
Oh, ok. Thanks.
