### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by harshhhdev** [CodingTrain/website#2885]
Add a custom scrollbar which fits the theme of the website. Doing so if fairly easy.

Note, this won't work for Firefox. The scrollbar will just show on Chrome and Chromnium based browsers. 

```css
/* width */
::-webkit-scrollbar {
  width: 10px;
}

/* Track */
::-webkit-scrollbar-track {
  background: #ffffff; 
}
 
/* Handle */
::-webkit-scrollbar-thumb {
  background: #000000; 
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #000000; 
}```

**Comment by jhaashutosh** [comment]
Hi, i want to work on this issue, kindly assign it to me.

**Comment by gruselhaus** [comment]
Got for it :)

**Comment by KobeLiesenborgs** [comment]
Hey Guys!

Sorry for the slow reply, we didn't really use the issues system on here recently.
We will move to a new website repo soon and would love your feedback on there!

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!

Hope to see you there!
