### ISSUE TITLE
Hacktoberfest Mistake Resolution

### ISSUE THREAD

**Issue by violetcraze** [CodingTrain/website#2900]
Hello @milan-micic @Lemmings42 @ItayNaveh @twentyonedot @decrecementofeliz @TahsinTariq @iccir919 @chepecarlos @Immodal @Ivan-Denisovich-py @anjakhan @SibianDG @michalinaj @JacobGeoGeek @IngridGdesigns @dansarno @PlaidDroid @NCProductions @DesignrKnight @aanchal-adk @Ezwann @melissa-24 @vr1e @gmgalvan @hootio @notshekhar @b-yogesh @ajuancer @Ashikpaul @amnindersingh12 @dummy26 @FEDQK @D-T-666,

This is update for those effected by my mistake around Hacktoberfest. If you were not participating in Hacktoberfest or complected Hacktoberfest without problems no need to read any further.

So for those not aware of what happened here's a quick recap. On Nov. 2ed I was cleaning up from Hacktoberfest and I made a mistake removing the `Hacktoberfest` label from the repository not knowing that pull requests were still maturing. If you participated in Hacktoberfest this terminology probably makes sense, but if not it means Hacktoberfest was waiting 14 days to see if pull requests were rejected. This means if you made a pull request in the last 13 or so days of October to the `CodingTrain/website` repository then it was marked as invalid. I apologies for this mistake on my part and I also apologies that it took me about a day to realizes what was happening despite multiple people reaching out.

Following this I tried to correct the issue by adding the `Hacktoberfest` label to the repository again and adding the `hacktoberfest-accepted` label to all the pull requests that might have been effected. Something which I later learned didn't work, because they were actions that were only acknowledged by the Hacktoberfest system during October. I began a long email exchange with the Hacktoberfest Team. I won't bore you with the whole exchange but it eventually resulted in this email from Hacktoberfest on Nov. 17th:

>Hi Violet,
>
>I've just checked in with our development team -- there won't be any code changes made to edit the behaviour of the Hacktoberfest app, the current behaviour is the correct and intended behaviour based on how the Hacktoberfest rules were implemented this year.
>
>Happy Hacking,
>The Hacktoberfest Team

This means there's no way correct this through Hacktoberfest. The Coding Train will be offering anyone who didn't finish Hacktoberfest because of this mistake some Coding Train stickers or a donation to plant a tree. If you think you were effected by this problem please email me (violet@thecodingtrain.com) with a screenshot of you Hacktoberfest profile page, your choice of stickers or tree, and your address if you you choose stickers. It may take a few months to send you stickers, The Coding Train is not know for it's speed when it comes to rewards.

I'll close this issue in two weeks but feel free to email me after that, it's just to keep the repository from being cluttered with issues.

Feel free to email me or comment below with any concerns or questions.

Sincerely,

Violet

**Comment by DesignrKnight** [comment]
Hey @violetcraze and entire CodingTrain Team. This is an awesome gesture from your end. It makes me glad to see people going out of the ordinary to keep the community happy. 

Thank you

**Comment by 007vedant** [comment]
@violetcraze and the team, great gesture on your end guys. Extremely happy to see this. Thank You. Way to go 💪

**Comment by b-yogesh** [comment]
@violetcraze and team, this is great gesture from your side. Really makes me happy about being a part of this community to contribute more. Thanks a lot again. 😀

**Comment by vr1e** [comment]
@violetcraze Thank you VERY MUCH for all the effort and everything you did! 🚀

The whole miscommunication was on digitalocean and hacktoberfest side. None of us knew how their changed system works as they changed it during the event and did not inform the participants clearly.

I loved your site and will be glad to get involved in the future and recommend it to everyone learning.

All the best to you! 🎁

**Comment by Ivan-Denisovich-py** [comment]
@violetcraze This is why we love this community so much! Nothing but the best of wishes to you Violet

**Comment by NavidMansuri5155** [comment]
@violetcraze  Hacktoberfest No Mistake

**Comment by Adelopoanas** [comment]
This is awesome
