### ISSUE TITLE
Qs: Calculate Error in Polynomial Linear Regression

### ISSUE THREAD

**Issue by johnneuland** [CodingTrain/website#2904]
This is more of a question. I went through the youtube tutorial for this:
https://github.com/CodingTrain/website/tree/main/CodingChallenges/CC_105_tf_polynomial_regression/P5

and was wondering if it is possible to calculate a training error during the polynomial regression? Or is there another way to obtain a percentage to see how overfitted/good our model is with the current drawn points?

**Comment by violetcraze** [comment]
Unfortunately I don't know the answer to this question. Issues here are mainly for pointing out problems with the webiste. You're much more likely to get an answer by asking on The Coding Train's Discord. Here's an invite if you're interest: https://discord.gg/hPuGy2g
