### ISSUE TITLE
Having issues with the new Shape Classifiers NN

### ISSUE THREAD

**Issue by RockoonTechnologies** [CodingTrain/website#2915]
Trying the new provided training script, with the mouse script extension (https://github.com/CodingTrain/website/blob/main/CodingChallenges/CC_158_Shape_Classifier/mouse/sketch.js)

I followed all the steps, tried debugging on my own, etc. Maybe I'm just being dumb, but I keep getting the same error: 
`Error: Based on the provided shape, [1,64,64,4], the tensor should have 16384 values but has 65536`

Possibly there is an issue, maybe I'm being dumb?

**Comment by w-A-L-L-e** [comment]
Indeed I get the exact same error when you train a new model and use the saved model.json, model_meta.json and model.weights.bin files
```
Error: Based on the provided shape, [1,64,64,4], the tensor should have 16384 values but has 65536
    at C (ml5.min.js:18)
    at Pn (ml5.min.js:18)
    at Object.jn (ml5.min.js:18)
    at t.<anonymous> (ml5.min.js:306)
    at w (ml5.min.js:373)
    at Generator._invoke (ml5.min.js:373)
    at Generator.t.<computed> [as next] (ml5.min.js:373)
    at i (ml5.min.js:66)
    at ml5.min.js:66
    at new Promise (<anonymous>)
gotResults @ sketch.js:59
```
why is this closed?
