### ISSUE TITLE
Search utility?

### ISSUE THREAD

**Issue by richardr91** [CodingTrain/website#2925]
I'd love to see a search bar utility on the site! While the organizing of content into sub categories is useful, the ability for visitors to more specifically search for content related to the topic or problem they're looking to solve would add to better navigation of the site, especially if content is tagged with keywords.

**Comment by violetcraze** [comment]
@richardr91 Thanks for the suggestion. I certainly think a search feature would be nice however it would be much easier to add if the site was full stack and not just front end. It might be more realistic to add a search this site with google box at least to have some search.

I might look at doing this at some point, but if someone wants to try adding this that would be great. It would have to work on both mobile and desktop as well as be accessible to screen readers to be merged. But if someone wants to tackle this just comment to say you're working on it and feel free to ask questions.

**Comment by richardr91** [comment]
I'm pretty new to coding and programing, but I might give this a try. (What I lack in experience, I make up for with enthusiasm!) Any assistance/advice is welcomed nonetheless!

**Comment by KobeLiesenborgs** [comment]
Hey Kitty!

Sorry for the slow reply, we didn't really use the issues system on here recently.
We will move to a new website repo soon and would love your feedback on there!
The reason we have no search bar is that the website is currently a static website.

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!

Hope to see you there!
