### ISSUE TITLE
Can anyone write an oop processing version of CC_035_4_TSP_GA

### ISSUE THREAD

**Issue by psamead** [CodingTrain/website#2978]
I am learning the Processing and trying to convert Daniel’s ‘Traveling Sales Person’ JavaScript to the Java Processing in the Object Oriented style using the genetic algorithm idea. But my code seems it is not constantly generating orders. Can anyone write an oop version of the CC_035_4_TSP_GA

**Comment by KobeLiesenborgs** [comment]
Hey PSAMead!

Sorry for the slow reply, we didn't really use the issues system on here recently.
For requests like this I would recommend joining [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!

Hope to see you there!
