### ISSUE TITLE
CC 59 Steering Behaviors: Font Loading Fails

### ISSUE THREAD

**Issue by da091005** [CodingTrain/website#3214]
On the P5 web editor version of Steering Behaviors, sketch does not execute due to font not loading. I don’t know if this is an issue with the web editor loading the font or the font availability. 

-UnOriginalPun

**Comment by KobeLiesenborgs** [comment]
Hi Da!

Unfortunately with the big amount of videos it is near impossible to keep everything up to date that deprecates.
That being said you can always add a community contribution that has an updated version!

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!
