### ISSUE TITLE
Traveling Salesman Problem to fix

### ISSUE THREAD

**Issue by jjuniorc** [CodingTrain/website#3240]
After read books about Traveling Salesman Problem it is considered a Non-deterministic Polynomial Time Complete as it consider that salesman will back to start point. So your solution may be incomplete because you are not considering that salesman need to return to beginning.

Here is where I am checking this information: Cormen, Thomas H., ed. (2013) Algorithms Unlocked. The MIT Press

But in my mind it can also be a NP Time Complete algorithm without return to start point. I did a checkbox to include the return to beginning in distance count. I believe that you can improve your solution to be better suited to some computer science literature's.

Please, let me know if I am correct in my analysis

![ksnip_20210613-174103](https://user-images.githubusercontent.com/12830389/121821299-939de700-cc6e-11eb-89c0-70348b6c80fd.png)

**Comment by KobeLiesenborgs** [comment]
Hi Darthmall!

The algorithm can definitely be improved and changed for actual use, for the website however we tend to stick to the examples from the videos! Your point is valid for sure though!

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!
