### ISSUE TITLE
Make all conversations in this repository able to be replyed by non-collaborators and collaborators

### ISSUE THREAD

**Issue by iKittyCode** [CodingTrain/website#3290]

**Comment by iKittyCode** [comment]
sorry i meant issue

**Comment by KobeLiesenborgs** [comment]
Hey Kitty!

Sorry for the slow reply, we didn't really use the issues system on here recently.
We will move to a new website repo soon and would love your feedback on there!

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!

Hope to see you there!
