### ISSUE TITLE
Wander Video Test Failing

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#3343]
The wander video tests are failing #3341, I'm not sure if it's a broken link to a web editor sketch or that the web editor API / way that we check sketches is not working properly. I'm going to go ahead and merge since I believe this shouldn't stop the page from publishing, but wanted to check!

<img width="904" alt="Screen Shot 2021-09-16 at 8 45 16 AM" src="https://user-images.githubusercontent.com/191758/133614572-cc64b48f-d3d7-4d89-a4f0-33c1e877a9f3.png">

**Comment by gruselhaus** [comment]
@shiffman Yes, this happens sometimes when the request to the API from the web editor fails. You can just restart the job, then it should go through.

<img width="252" alt="Bildschirmfoto 2021-09-16 um 14 53 33" src="https://user-images.githubusercontent.com/33380107/133615702-514a5f5b-c9d4-45aa-a269-95072748f40a.png">

**Comment by shiffman** [comment]
Thank you!
