### ISSUE TITLE
Community Contribution: Empowering everyone to code with Google's Eye

### ISSUE THREAD

**Issue by Aniket762** [CodingTrain/website#3372]
## Community Contribution 

Link to Github: https://github.com/Aniket762/playground
Link to blog: https://dev.to/aniket762/empowering-everyone-to-code-with-google-s-eye-49e9

I would be happy to have my project shared on The Coding Train's social media!

**Comment by Aniket762** [comment]
Hey, @gruselhaus @duskvirkus we developed `Playground` in an MLH hackathon in which we were the overall winners. But being a beginner developer it's difficult for me to take this prototype to production. Coding Train's social media will help the project get reach and ultimately the finished product with the community support can help 85% more people get started with coding because our project playground empowers everyone to code, people who cannot afford a personal computer can now code with Playground. 

Let me know how I should proceed so that our content gets featured!

**Comment by KobeLiesenborgs** [comment]
Hi Aniket!

This isn't quite the correct place to request a collaboration or shoutout of your system.
Unfortunately the issues system on this repo wasn't used for a while so apologies for the late reply!

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!
