### ISSUE TITLE
Self avoiding walk with recursion.

### ISSUE THREAD

**Issue by hassam7** [CodingTrain/website#3443]
The [recursive version of self avoiding walk](https://editor.p5js.org/codingtrain/sketches/UPxBk1YiB) always yield the same result (shown in screenshot below) where [as its backtracking counterpart](https://editor.p5js.org/codingtrain/sketches/dRWS3A9nq) yields different result on each execution.
![Screenshot 2021-12-08 at 2 02 24 AM](https://user-images.githubusercontent.com/10061444/145105671-2d769d9b-ee69-4a18-aca6-2812dd73c98d.png)

I think this is because of the following code:
```
 if (selfAvoidingWalkHelper(path, visited, desiredLength, i + 1, j)) {
    return true;
  }
  if (selfAvoidingWalkHelper(path, visited, desiredLength, i - 1, j)) {
    return true;
  }
  if (selfAvoidingWalkHelper(path, visited, desiredLength, i, j + 1)) {
    return true;
  }
  if (selfAvoidingWalkHelper(path, visited, desiredLength, i, j - 1)) {
    return true;
  }
 ```
Instead of making fixed choices (right,left,top and bottom) some randomisation needs to be added

**Comment by KobeLiesenborgs** [comment]
Hi Hassam!

The algorithm can definitely be improved and changed for actual use, for the website however we tend to stick to the examples from the videos!
