### ISSUE TITLE
Broken links on Youtube - 165: Slide Puzzle

### ISSUE THREAD

**Issue by chepecarlos** [CodingTrain/website#3506]
I found an error in the description of the last "Coding Challenge"

[Coding Challenge 165: Slide Puzzle](https://www.youtube.com/watch?v=uQZLzhrzEs4)

### First

Current:
`https://thecodingtrain.com/CodingChallenges/165-slidingpuzzle.html `
Correct:
`https://thecodingtrain.com/CodingChallenges/165-slide-puzzle.html ` 

### Second

Current: 
`🎥 Coding Challenge 164 Bending Time SlitScan: /CodingChallenges/164-time-slitscan.html `
Correct: 
`🎥 Coding Challenge 164 Bending Time SlitScan: https://youtu.be/hckvHFDGiJk` 

I think the description generator was executed, with another file name, when I run  `npm run yt-descriptions` the correct description comes out

![imagen](https://user-images.githubusercontent.com/1410988/152231084-fc3a96a4-6957-403f-a41c-d1e129c82adc.png)

**Comment by KobeLiesenborgs** [comment]
The description was made before the website page was finalised, thanks for reporting the mistakes! I fixed the description!
