### ISSUE TITLE
Re-design text centering?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#355]
I think the text centering sometimes looks a little strange, I think these elements could use a re-design.

<img width="1241" alt="screen shot 2018-01-06 at 5 14 26 pm" src="https://user-images.githubusercontent.com/191758/34644460-21f0d9c8-f305-11e7-8896-acd2a3de4b5f.png">

<img width="1338" alt="screen shot 2018-01-06 at 5 15 38 pm" src="https://user-images.githubusercontent.com/191758/34644467-3eabe918-f305-11e7-9326-2febfffe5bb5.png">

**Comment by nilsweb** [comment]
I will try to come up with something better over the next couple of days. Any suggestions?

**Comment by shiffman** [comment]
I'm the worst at this sort of thing, but I would at least start with just left aligning this text?  Perhaps the title and description of each page should be a "card" like each video? Not sure if that will be better or worse.

Also, related to this I removed the very large header / logo image. Would be great to include somehow but it takes up way too much vertical space. Maybe it's only for the landing page or perhaps there can be a little train (animated!) driving by on the top nav?

**Comment by Link2Twenty** [comment]
I thought the image looked good but it does feel like a landing page only type thing.

Jekyll lets you do if statement like so.

```XML
{% if page.url == "/" %}
<img src="{{ '/assets/images/header.jpg' | relative_url }}">
{% endif %}
```
