### ISSUE TITLE
Live stream schedule

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#356]
The live stream page could include an "upcoming" schedule that I could maintain?

**Comment by nilsweb** [comment]
It actually already does. If you add a new file, say `_Streams/114-second-stream-of-2018.md` and set the date property to a future date (and time) like `date: 2018-01-12 16:00`, the section "Upcoming Streams" should be visible at the bottom of the front page.

Full example:
``` markdown
---
title: Second Stream of 2018
video_number: 114
date: 2018-01-12 16:00
---

Topics:
- continue machine learning
- read random numbers
- do something else
```

![Rendered output](https://user-images.githubusercontent.com/12577464/34652714-4bb786ac-f3e2-11e7-8d29-e4cb4b163056.png)

**Comment by shiffman** [comment]
@nilsweb awesome, I will experiment with it this week!

**Comment by shiffman** [comment]
This works great, and I've got tomorrow's live stream on the page. I think a better place would be the top of the "streams" page (though it could still be on the bottom of the front page too?).

**Comment by nilsweb** [comment]
Added it to my to do list. FYI: “Upcoming Stream” cards will be hidden after the next build after they have happened as long as there isn’t a `video_id` set. So you can just update them without the need of recreation.

**Comment by Jamesinvi** [comment]
Is it possible to add a "Live right now!" animation or something? or is this already in place?

**Comment by nilsweb** [comment]
@Jamesinvi Right now, there's just the next stream shown on the landing page but an extra animation should be possible. This might also be a great way to have spontaneous streams listed since they are often not included in the schedule. Any ideas on how this should be integrated into the design?

**Comment by Jamesinvi** [comment]
@nilsweb not sure but a blinking red circle might be a good way of doing it. I am just starting to use javascript/html so I dont really have a good grasp of what a good implementation would be

**Comment by spiray** [comment]
@nilsweb I would add a red badge on the right of the "Second Stream of 2018" that says Live Now like YouTube has.

**Comment by nilsweb** [comment]
@Jamesinvi That could be possible but maybe we should integrate it e. g. somewhere in the header so it is visible across all pages on the website?

**Comment by nilsweb** [comment]
Closing this now since it is not really used anymore due to some issues.
