### ISSUE TITLE
Tutorials vs. Courses?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#357]
I wonder if "tutorials" and "courses" are really the same thing: a higher level topic that organizes a bunch of playlists.

Is it a good idea to keep them separate? Is there a different term that would work? Or just stick with "courses" maybe . . or "tutorials"?

**Comment by nilsweb** [comment]
Currently the website thinks of "courses" as just of a collection of playlists containing videos and "tutorials" simply as playlists of videos.

Technically there isn't much of a difference. We just need to decide on how to group everything, the rest should be easy.

**Comment by shiffman** [comment]
@blinkityblank what do you think about this?

**Comment by AryanGitHub** [comment]
So , what was the ultimate result of Tutorial vs courses?? Do you guys figured it out??

**Comment by nonas-hunter** [comment]
In my opinion I would **get rid of tutorials and just have courses**.

After combing The Coding Train youtube channel I realized: if you combine all the tutorials (each tutorial is a playlist of videos) you just get a course (a collection of playlists) on _The Foundations of Programming in JavaScript and P5.JS_.

@blinkityblank  and @nilsweb if you think this is a good idea I would gladly turn the tutorials into a course in my forked version of the website and submit a pull request with the change.

**Comment by shiffman** [comment]
Thanks for this research @nonas-hunter! I am really confused about the best way to organize all of this material but willing to and excited to try any and all ideas! Maybe what is best is to just try to get everything that is in the channel here somewhere on the website with a markdown page and then start re-organizing?

I agree with you in principle that a "tutorial" is a playlist of ~5-10 videos whereas a "course" is a grouping of these playlists?

I'm tagging @joeyklee who is working on some similar ideas related to organizing collections of resources into "courses."

**Comment by joeyklee** [comment]
Hello All + greetings!
+1 to making a distinction between `tutorial` and `course`. Like @shiffman mentioned, I might conceptualize that a `course` is comprised of several `tutorials`. A `tutorial` is then comprised of 1 or more `videos` and additional references.

```
COURSE 
      |
      ------ TUTORIAL1
      |                 |
      |                 ------ VIDEO1, VIDEO2, VIDEO3
      | 
      ------ TUTORIAL2
      |                 |
      |                 ------ VIDEO4, VIDEO5, VIDEO6            
      |
      ...
```

**Comment by nilsweb** [comment]
I would also like to re-do how videos are organized. The only reason why I chose to distinguish between tutorials and courses that way was to resemble the channels' organization as close as possible. That however lead to a somewhat complex logic in Jekyll's templates. Everything that would simplify this I would greatly appreciate!

Like @shiffman said, adding everything that's missing (which is still quite a lot) should maybe done beforehand even though we might have to change some things at a late stage again. That way, if we find something we haven't thought of before we can incorporate that into the new structure as we go.
