### ISSUE TITLE
Challenges with p5.js and Processing code

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#359]
Some challenges (or in an ideal world perhaps all?) have both p5.js code and Processing code. The Processing code does not run as an online demo. An example is the Langton's Ant. Right now there is only Processing code which is linked from "Get the Code". The "Live Example" points to 404. This is what I'm thinking:

```
repository_p5: /CC_89_langtonsant_p5
repository_Processing: /CC_89_langtonsant
```

"Live Example" would appear only if there was a "repository_p5" link? And download buttons would appear for one or both or p5 / Processing?

Would something like this work?

**Comment by shiffman** [comment]
As discussed on slack, if neither is present, then a message says "code now available yet" would appear . . .perhaps with a link to a wiki on how to contribute it.

**Comment by nilsweb** [comment]
That would probably be a good idea. As for now you can also set `live_example: false` (or to some URL) to disable (or change) the location of the live example.

I think that it should also be possible to detect, if a file already exists using Jekyll. Therefore we could stick with the current `repository` property and let Jekyll automatically figure out what's available so there would be no need to update the challenge's definition file when adding new code.
This would only require a standardised naming scheme like `CC_XX_tile_p5` for p5 and `CC_XX_title_processing` for Processing.

Maybe we could also add a static page that runs the web version of a Processing sketch but I haven't worked with those before so I don't know if this is could be done easily.

**Comment by shiffman** [comment]
Awesome, this sounds great. I don't mind maintaining an extra `live_example` field if that makes it easier than a naming convention / auto-detection. 

It's not worth trying to get web versions of Processing sketches to run, I'm either doing it in Processing b/c it's not appropriate for the browser or if it is, I might as well port to p5.

**Comment by nilsweb** [comment]
The only reason for having an extra `live_example` field is just so you can turn it off (by setting `live_example: false`) or link to an external resource (e. g. a Node.js-based project hosted on Heroku). So it wouldn't make it easier nor more difficult.

I'll make some experiments on auto-detection and report back if it would work or not.

**Comment by shiffman** [comment]
all sounds great! I like the idea of being able to link to an external resource. For some of the videos the example code or demo ends up living in a different repo.

**Comment by nilsweb** [comment]
So I'll add the ability to reference external repositories as well since it is now supported at the moment.
