### ISSUE TITLE
NeuralNetworkData.js:218 Uncaught TypeError: Cannot read properties of undefined (reading 'xs') HELP (Coding Challenge #158)

### ISSUE THREAD

**Issue by Gabocota** [CodingTrain/website#3599]
Hello, I am trying to do Shape Classifier Neural Network with ml5.js Coding Challenge #158 and I have been fighting this error for over an hour. 
![image](https://user-images.githubusercontent.com/88735758/160975757-0ef1d1ee-6f74-4dbb-8fff-84764db48ee8.png)
This is how my code looks. This is so frustrating. I don't know what I'm doing wrong.
![image](https://user-images.githubusercontent.com/88735758/160975872-be819e4d-94d3-4b18-ac9d-2039f6b2cb8f.png)
![image](https://user-images.githubusercontent.com/88735758/160975888-cb96ed2b-f348-400d-8650-016339df7ead.png)
Because the purpose of this is to learn in every part I would pause and re-write what he was doing to understand. This is not a copy-paste but I don't think I have anything mistyped.
Please help!

*I know about the "true" on debug: needing to be a boolean. It doesn't work either way.

**Comment by KobeLiesenborgs** [comment]
Hey Gabocota!
This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

Hope to see you there!
