### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#367]
Might be nice for individual video pages to link up in the hierarchy. For example if I'm on this page:

http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/2-regular-expressions/2.3-character-classes.html

I should be able to get back to the [all regex videos](http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/2-regular-expressions/) list and from there back to the [programming with text course page](http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/) and from there to the [all courses page](http://codingtrain.github.io/Rainbow-Code/Courses/)?

Also, when I go to courses I don't see how to get to just one course. I found this page just by guessing the url:

http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/

Finally, I think I prefer non html permalinks i.e.

`http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/2-regular-expressions/2.3-character-classes/` 

over 

`http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/2-regular-expressions/2.3-character-classes.html.`

I recall there's a way to specify the url in jekyll?

Or maybe this is silly and html links are perfectly good?

**Comment by nilsweb** [comment]
Like a breadcrumb navigation? Should be fairly easy to implement.

About the courses: When you navigate to https://codingtrain.github.io/Rainbow-Code/Courses/ there should be a preview of each course (consisting of three videos). When you click on "Watch all Sessions", it should take you the the corresponding page.

I also highly prefer to use the "pretty" URL format. Unfortunately Jekyll then generates the index pages (for coding challenges/tutorials/...) like this: https://codingtrain.github.io/programming-with-text/2-regular-expressions/index
With Jekyll 3.7 which came out just a few days ago (yay!) this should be possible to overcome somehow. This also enables some other cool features but I will file separate issues once I've played around with it a little bit.

**Comment by Link2Twenty** [comment]
*Raises hand timidly*

I may have missed something but web browsers presume the `.html` as long as you miss the trailing `/`, as that means open as a directory.

Meaning these 2 URLs are the same as far as the browser knows.

- [http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/2-regular-expressions/2.3-character-classes](http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/2-regular-expressions/2.3-character-classes)
-  [http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/2-regular-expressions/2.3-character-classes.html](http://codingtrain.github.io/Rainbow-Code/Courses/programming-with-text/2-regular-expressions/2.3-character-classes.html)

but if you put in that trailing `/` you're telling it to look for an index file here `Rainbow-Code/_Courses/programming-with-text/2-regular-expressions/2.3-character-classes/` which doesn't exist.

**Comment by shiffman** [comment]
I was thinking about the top navbar today and thought up this list. . it's probably too many for a navbar. Thoughts on what we should keep, eliminate?

* coding challenges
* beginners (beginner p5.js and processing playlists?)
* courses (nature of code, a2z, intelligence and learning)
* live archives (better term than "streams"?)
* open source (for github, CI, and other dev-ops videos?)
* contribute
* about

**Comment by MeaningOf42** [comment]
Perhaps the lesser used sections such as about and live archives could appear at the bottom of the page (like the link to the about page on github). I know there is already a menu on the bottom of the the coding train site (nature of code - learn processing - shiffman.net) but it doesn't appear too crowded, maybe the about page could be put there, or underneath.

**Comment by suekam** [comment]
I think it is not too much for a nav bar... as it's always better to make important links more approachable. Perhaps we can just group them, so fewer items are initially visible and it looks cleaner on the header. Example below:

- coding challenges
- tutorials     
     - beginners
     - courses
- live archives
- about
- contribute
     - open source
     - other (like videos/tutorial making?)


Lastly, the GitHub link can be placed in the top right corner, use an icon/badge to represent it 

If anyone proposed or implemented anything already, please let me know! I am new to here :D
