### ISSUE TITLE
Feed-forward matrix visualization

### ISSUE THREAD

**Issue by YoDevil** [CodingTrain/website#371]
Hopefully this is the right place to post this!

After watching you struggle on the live stream, I thought I could help out. 
After a bunch of tries I believe the most visually correct visualization of the concept that feed-forward is just matrix multiplication is how I sketched it here:
![matrix](https://user-images.githubusercontent.com/8167495/34890311-b3f5eacc-f7d1-11e7-90c7-1aaf1f819ea0.png)
The Inputs vector should be a **row vector** and should come first in the multiplication (I*W), so that when applying the `first row ⨯ first column` algorithm you actually have the weighted sum of the 3 inputs by its weights connecting it to the first hidden neuron.
The Weights matrix has **n_input rows** and **n_hidden columns**, so that everything is logically in place, and the _row first, column second_ rule for indeces is respected.
The output now is a new row vector, ready for the next layer.
Note that i'm bypassing the bias, but that would be to be a row vector aswell to be summed to the outputs.

This visual rapresentation actually makes logical sense and is consistent with the graph notation. Obviously in the code it wouldn't matter, since notation doesn't matter as long as you're consistent.

( There is the other possibility of doing the opposite with inputs as a column vector, but that would need the Weights matrix to be **transposed** before being multiplied with the inputs in the other order: W*I. Basically one of the two matrices in your video example would need to be transposed, and the most immediate way would be to transpose the inputs vector making it a row, that's why I chose this way in my sketch )

I would suggest re-recording the video, as it was quite confusing even to one that _should_ be familiar with this stuff ;d

**Comment by shiffman** [comment]
Thank you for this very helpful feedback! I am going to re-record the video next week and these comments are very useful! The standard notation I've seen in most materials is showing the inputs as a column vector so I may still stay with that, but thank you so much for all these excellent tips!

**Comment by YoDevil** [comment]
@shiffman in that case you would need to transpose the Weights matrix to have it mathematically correct. I've seen a lot of confusion in online examples, some do but others do not

**Comment by kwichmann** [comment]
Yes, input as column vector seems to be the most common notation
