### ISSUE TITLE
Migrate all videos to the new format

### ISSUE THREAD

**Issue by vimkat** [CodingTrain/website#373]
Collections that need to be migrated:
- [x] Coding Challenges
- [ ] (Guest) Tutorials
- [ ] Courses
- [ ] Streams

Things that need to be done when migrating:
- create a definition file (`.md`) for each video with its title, description, video number, video id and repository/live example (if code is present)
- migrate community contributions from the old READMEs to the new format
- add related links, videos, books/papers, etc.
- add a note to the old `README.md` files

To see a full list of all available options for each video, have a look at the [Content Contribution Guide](https://github.com/CodingTrain/Rainbow-Code/wiki/Content-Contribution-Guide).

**Comment by Merijn-DH** [comment]
@blinkityblank are you currently working on adding the last few CC .md files or can I take a shot at it?

**Comment by blinkityblank** [comment]
You can go ahead and add the last few, I'm actually working on reviewing the ones that I already made(adding links my script missed, adding author, etc).
