### ISSUE TITLE
Scope Coding Challenge 50

### ISSUE THREAD

**Issue by nucliweb** [CodingTrain/website#398]
Hi @shiffman 

In the **Coding Challenge 50** I saw that the condition `if (attempts > 1000)` never is true because you've `var attempts = 0` into each the loop in `draw()` method.

I sent you a [PR](https://github.com/CodingTrain/Rainbow-Code/pull/397) to fix this in **Processing** and **P5.js**

**Comment by ZwergB** [comment]
PR #397 got closed, therefore this issue can be closed as well.
