### ISSUE TITLE
Deprecate Coding Challenge README's

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#400]
Following up from #389, we can now remove the community contributions from the Coding Challenge README's and add a note to each one how to contribute with the new system.

**Comment by shiffman** [comment]
Noting that as each one is done, the community contributions need to be copied over to the new markdown file associated with each challenge!

**Comment by Merijn-DH** [comment]
Is it ok if I assign this to myself? I'm done up to CC 68 at the moment.

**Comment by shiffman** [comment]
Yes, of course, thank you @Merijn-DH!

**Comment by Merijn-DH** [comment]
I'm so sorry I have been inactive for the past few weeks, I'll get to this very shortly!

**Comment by Fraasi** [comment]
This transition is long done and issue could be closed.
@shiffman Could you confirm?

**Comment by shiffman** [comment]
indeed!
