### ISSUE TITLE
2048 Processing Solved

### ISSUE THREAD

**Issue by sergiuwd** [CodingTrain/website#408]
Hi, @shiffman 
I have completed the "2048" game you were building last night and fixed the issues that you had. Have a look here:
https://github.com/sergiuwd/Processing-2048

I could not create a fork since it's not uploaded here yet. It's a little messy, but I refactored some stuff and made movement in all directions available. Also, the bug you had when you ended the stream is fixed and I added some improvements (game over screen, score calculation, colors based on value).

**Comment by shiffman** [comment]
Thank you, this made my morning! What a mess I made yesterday, this is so lovely and awesome. Let's revisit when I get the challenge finished and code posted.

**Comment by sergiuwd** [comment]
@shiffman You're welcome! Thank you for sharing your knowledge with us!
