### ISSUE TITLE
Improve CC_71_minesweeper

### ISSUE THREAD

**Issue by jJayyyyyyy** [CodingTrain/website#458]
## Env

* Windows + Chrome

<br>

## Description

[CC_71_minesweeper.](https://github.com/CodingTrain/website/tree/master/CodingChallenges/CC_71_minesweeper)

Too many CPU resources are taken up, mainly due to nested for-loop in `function draw()` in `sketch.js`.

<br>

## Suggestion

In order to avoid a high CPU usage(40%+), some changes need to be made to optimize the performance.

*   **Step 1**

    `grid[i][j].show()` is removed from the nested-for-loop in function `draw()`.

    ```javascript
    function draw() {
        // empty
    }
    ```

*   **Step 2**

    [FPS](https://github.com/processing/p5.js/wiki/Optimizing-p5.js-Code-for-Performance#frames-per-second-fps) is changed from 60(default) to 10. And we have to draw the gameboard in `setup()`.

    ```javascript
    function setup() {
        createCanvas(401, 401);


        /*set fps to 10*/
        frameRate(10);
        /***************/


        // ... other setup remains the same
        // ********************************

        /* draw the gameboard */
        for (var i = 0; i < cols; i++) {
            for (var j = 0; j < rows; j++) {
                grid[i][j].show();
            }
        }
        /**********************/
    }
    ```

*   **Step 3** (main point)

    Since `mousePressed()` will trigger `grid[i][j].reveal()`, it would be good to call `show()` inside `reveal()`.

    ```javascript
    Cell.prototype.reveal = function() {
        this.revealed = true;
        this.show();    // this.show() is placed here


        if (this.neighborCount == 0) {
            // flood fill time
            this.floodFill();
        }
    }
    ```

*   **Step 4**

    Lastly, we want to modify the function `gameover()`.

    ```javascript
    function gameOver() {
        for (var i = 0; i < cols; i++) {
            for (var j = 0; j < rows; j++) {
                // grid[i][j].revealed = true;
                grid[i][j].reveal();
            }
        }
    }
    ```

<br>

## Demo and Code

* [Demo after change](https://jjayyyyyyy.github.io/MineSweeper/Demo2) is basically the same as the original, but with fewer CPU usage( <10% ).

* Details can be found [in this repo](https://github.com/jJayyyyyyy/MineSweeper).

**Comment by meiamsome** [comment]
Hey, this is a good idea, however the preferred way to do this in p5js AFAIK is to set `noLoop()` in `setup` and trigger a render with `redraw()`. https://p5js.org/reference/#/p5/redraw
I don't know if that's worth adding to the example, though
