### ISSUE TITLE
speechRec not working in chrome

### ISSUE THREAD

**Issue by FaraazAttariSaqibi** [CodingTrain/website#505]
i am using xampp local server in windows 10, and chrome
the entire process, whenever i run it in chrome, it shows a red blinking dot in tab, but don't work anything.
--------------------------------------------------------
function setup() {
  noCanvas();
  let speech = new p5.Speech();
  let speechRec = new p5.SpeechRec('en-US', gotSpeech);
  speechRec.continuous = true;
  speechRec.interimResults = true;
  speechRec.start();

  let bot = new RiveScript();
  bot.loadFile("script/brain.rive", brainReady, brainError);

  function brainReady() {
    console.log('ChatBot Ready!');
    bot.sortReplies();
    //let num = floor(random(10)) + 1;
    //console.log(num);
    //let reply = bot.reply('local-user', 'set ' + num);
  }

  function brainError() {
    console.log('ChatBot Error!');
  }

  let button = select('#submit');
  let user_input = select('#user_input');
  let output = select('#output');

  button.mousePressed(chat);

  function gotSpeech() {
    if (speechRec.resultValue) {
      let input = speechRec.resultString;
      console.log(input);
      user_input.value(input);
      let reply = bot.reply("local-user", input);
      speech.speak(reply);
      output.html(reply);
    }

  }

  function chat() {
    let input = user_input.value();

  }

}
----------------------------------------------------------
this is my code

**Comment by gruselhaus** [comment]
If this behaviour still exists raise an Issue at https://github.com/IDMNYU/p5.js-speech please.
