### ISSUE TITLE
Display Errors in IE

### ISSUE THREAD

**Issue by weinzierl-florian** [CodingTrain/website#523]
I saw some very ugly errors while looking at The Website using IE 
![2018-03-15 10_23_43-the coding train __ code repository - internet explorer](https://user-images.githubusercontent.com/10184013/37517248-0f114828-2911-11e8-9392-ac5e6aee8bf3.jpg)
D
![2018-03-15 10_23_28-the coding train __ code repository - internet explorer-2](https://user-images.githubusercontent.com/10184013/37522068-2ed0f9da-2923-11e8-8d86-a7a1a2dfa088.jpg)

**Comment by Merijn-DH** [comment]
Can you tell us what version of IE you are using? Using microsoft Edge seems to be working fine.

**Comment by weinzierl-florian** [comment]
I used IE 11, when I got this.
