### ISSUE TITLE
update p5.js version

### ISSUE THREAD

**Issue by Spongman** [CodingTrain/website#542]
@shiffman, i just noticed you were having issues with the friendly errors performance in your quadtree live stream. the reason for this is that you're using an old version of p5.js (0.5.16).

the latest version significantly reduces the overhead from **43**% (!!) of total CPU time in 0.5.16:
![image](https://user-images.githubusercontent.com/1088194/37927443-f594202e-30ee-11e8-91af-06801ff82591.png)

to less than **1**% in 0.6.0:
![image](https://user-images.githubusercontent.com/1088194/37927760-ccbfe59c-30ef-11e8-8925-fda7223a30cd.png)

**Comment by shiffman** [comment]
Oh this is so good to know, thank you! Glad to accept pull requests updating versions!

**Comment by micuat** [comment]
actually i noticed CC_02_MengerSponge_p5.js has another issue with p5.js version. it works properly with 0.5.11 which is shipped with the code, but when I updated the library to 0.6.0, nothing was rendered. I learned that I needed to add `normalMaterial()` to render with normal colors.

I wonder if all the codes need compatibility check with the latest p5js or just leave them as they are.

**Comment by Spongman** [comment]
can you try with 0.6.1 (which was just recently released) ?

**Comment by meiamsome** [comment]
Closing as fixed by #581
