### ISSUE TITLE
Coding Challenge: An AI which matches text with nlp!

### ISSUE THREAD

**Issue by ShreerangV** [CodingTrain/website#564]
See this:
`var s = 'I need to use a tissue'`
Now what you should do:
`var t = 'I want a tissue';`
`console.log(s.test(t));`
`//Should return true`
`t = 'Tissue please!'`
`console.log(s.test(t));`
`//Should return true again!`
`t = 'Can I have a tissue?';
//etc`

**Comment by nilsweb** [comment]
Moved to https://github.com/CodingTrain/Rainbow-Topics/issues/957
