### ISSUE TITLE
Coding Challenge: Rubik's Cube Solver using Neural Network

### ISSUE THREAD

**Issue by vladig98** [CodingTrain/website#573]
Coding challenge: A fully functional Rubik's cube solver. Something similar to this https://www.google.com/logos/2014/rubiks/iframe/index.html. Also use a neural network to create a solution for the cube and maybe then apply it. That'll be cool.

**Comment by nilsweb** [comment]
This sounds really interesting! I copied it over to the [Rainbow-Topics](https://github.com/CodingTrain/Rainbow-Topics) repository and it is now available [here](https://github.com/CodingTrain/Rainbow-Topics/issues/956).
