### ISSUE TITLE
CC 93 DoublePendulum p5.js buffer DPI issue

### ISSUE THREAD

**Issue by micuat** [CodingTrain/website#574]
I noticed that p5.js version of double pendulum renders incorrectly on my Microsoft Surface (probably on retina macs too). I needed to add `pixelDensity` here:

```
function setup() {
  createCanvas(500, 300);
  a1 = PI / 2;
  a2 = PI / 2;
  cx = width / 2;
  cy = 50;
  buffer = createGraphics(width, height);
  buffer.pixelDensity(1);
  buffer.background(175);
  buffer.translate(cx, cy);
}
```

should I go ahead and make pull request?

**Comment by shiffman** [comment]
ah, yes, thanks for this! Go ahead and pull request! The quality might suffer a bit of a high density display so it might be worth investigating other techniques for drawing the trail at some point... looking forward to your tweet!

**Comment by Merijn-DH** [comment]
Closing :) Further discussion can be done in the pr you made (#575)

**Comment by fepegar** [comment]
Sorry for necrobumping, but I removed the `pixelDensity` line and it looks fine on my retina display. Happy to submit a PR if you like.

**Comment by micuat** [comment]
@fepegar thanks, but it seems like already fixed here https://github.com/CodingTrain/website/pull/737

**Comment by fepegar** [comment]
That PR _added_ the line, I suggested _removing_ it.
