### ISSUE TITLE
Can't find the Processing version of the Coding Challenge #24: Perlin Noise Flow Field.

### ISSUE THREAD

**Issue by sebby13** [CodingTrain/website#58]
I only found the p5 version.

**Comment by shiffman** [comment]
I need to add it over here, but as a temporary measure there's this version: https://github.com/shiffman/Holo-2-Randomness/tree/master/Holo_02_Noise

**Comment by nilsweb** [comment]
It can now be found here: 
https://github.com/CodingTrain/website/tree/master/CodingChallenges/CC_024_PerlinNoiseFlowField_Processing
