### ISSUE TITLE
Starter code for tutorials

### ISSUE THREAD

**Issue by hammadshaikhha** [CodingTrain/website#584]
I am currently working my way through the p5js tutorial playlists. I am half way done and something I noticed is that although I can find the finished code under this repository, the starter code is not there. By starter code I mean the code Dan starts his tutorials with. I often found myself pausing the video at the start to type out the code from his screen, and then began to follow the tutorial.

I think it would be a good contribution for someone to also add the starter code of each tutorial. So then students can download the starter code, and follow along the video and update it. I can do this for future tutorials I go through and do a pull request later on if this seems like a good idea.

**Comment by JAnken123** [comment]
I took a look at the latest [video](https://youtu.be/nqiKWXUX-o8?t=8m26s) to try and understand what you meant. Are you referring to this?

![image](https://user-images.githubusercontent.com/14110063/40118745-0e22ef04-591b-11e8-83d9-023e14832e19.png)

**Comment by FriskyDev** [comment]
I have a folder called `_template_`, that has the attached files in it. Every time @shiffman yells "all aboard", I copy this folder to a folder of the name on the side of the train.

Note that you need to update the title in the `index.html` file.

[_template_.zip](https://github.com/CodingTrain/website/files/2718866/_template_.zip)

**Comment by KobeLiesenborgs** [comment]
Hey everyone!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

P.S. Sorry for the late reply, we didn't use the issue section of this repository for a long while.

Hope to see you there!
