### ISSUE TITLE
p5.js Stop rendering sketch on page when it hidden (Question)

### ISSUE THREAD

**Issue by Dissfall** [CodingTrain/website#590]
I have a test [website](https://www.geometryrain.me). It consist out of two sketches located sequentially. Simultaneous processing of two sketches is quite resource intensive. So, how can I stop rendering of second sketch when it is not visible to the user (outside the page)?

**Comment by spiray** [comment]
@Dissfall You can test for the display style value in an if statement and `return;` or `noLoop();` if it is `===` to none... so something like
``` 
if(canvas.style.display === 'none'){
     noLoop();
     return;
   }
```

**Comment by Dissfall** [comment]
@spiray Thanks for the answer. Now I found that ```canvas.style``` just not changing when it hide or visible (I'm not sure that I did everything right). It may be to look for another way...

**Comment by Merijn-DH** [comment]
What do you use to show and hide the sketch? You could include noLoop() and loop() in there?

**Comment by Dissfall** [comment]
@spiray @Merijn-DH I apologize to everyone, because I incorrectly formulated the question. I hope the correction will help to understand what I meant ...

**Comment by Merijn-DH** [comment]
The thing that is making this difficult is that you are using iframes to show your sketches in. To access the scroll level of the main page from within the frames you could try using `window.top.pageYOffset`, this should work as long as the sketches are located on the same domain.
