### ISSUE TITLE
Solar System P5.js 3D folder is missing

### ISSUE THREAD

**Issue by SAI16497307** [CodingTrain/website#593]
Hey Dan,
There is a p5.js missing. The solar system in 3d. the last one is CC_007_SolarSystemGenerator_p5.js
Would really appreciate if you could add the 3d one.

Thank you

**Comment by FriskyDev** [comment]
It looks like this was fixed by @madacoo

**Comment by gruselhaus** [comment]
@FriskyDev can you provide pull request that fixed the issue?

**Comment by FriskyDev** [comment]
@meiamsome  I agree, the #267 list seems to be fairly inclusive. And this one only specifically mentions 007, which is done.
