### ISSUE TITLE
7.1 Issue with a loop.

### ISSUE THREAD

**Issue by Coach1** [CodingTrain/website#596]
I've been noticing that the loops I've been creating are no longer working in the p5js editor. I even opened up an old project that I had saved, and it's not working either. If you can please help me, that would be great! Thank you!

![7 1 what is array issue with loop](https://user-images.githubusercontent.com/39306228/40062723-dfdbfd08-5829-11e8-90f0-6147a383a756.PNG)

**Comment by spiray** [comment]
@Coach1 This should be opened as an issue on the p5.js web editor repo. [Here is the link.](https://github.com/processing/p5.js-web-editor/issues)

**Comment by meiamsome** [comment]
This has been resolved upstream via https://github.com/processing/p5.js-web-editor/issues/635 so I'm going to close this now
