### ISSUE TITLE
using javascript in html

### ISSUE THREAD

**Issue by ctrembla** [CodingTrain/website#599]
So I started using javascript and html to make website and thought it be fun to convert my java games to javascript and place them on my website. I wrote code trying to see my javascript game from the html webpage, but i only see a white screen whenever i pull it up. 
here the html code:

`<!doctype html>
<html lang = "en">
<head>
	<title>Space Invaders</title>
</head>
<body>
	<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
	<script src = "spaceInvaders.js"></script>
</body>
</html>`

here the java script code:

`function setup(){
	createCanvas(400,400);
}

function draw(){
	background(0);
}`

**Comment by spiray** [comment]
@ctrembla You need to use `html, head, and body` tags.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
```
You can use that and put your script tags between the body tags. You are also using jQuery instead of p5.js...?
