### ISSUE TITLE
coding challenges

### ISSUE THREAD

**Issue by pujithreddy** [CodingTrain/website#608]
Star feild p5.js version not found and i want help with that

**Comment by meiamsome** [comment]
Hello, the p5.js version of Starfield Coding Challenge is found here:

Source Code:  https://github.com/CodingTrain/website/tree/master/CodingChallenges/CC_001_StarField_p5.js
Online Example: http://thecodingtrain.com/CodingChallenges/CC_001_StarField_p5.js/

Let me know if this isn't what you meant or I misunderstood.
Thanks!
