### ISSUE TITLE
classification dataset

### ISSUE THREAD

**Issue by MkLahane** [CodingTrain/website#619]
You should check this website it has tons of datasets for various machine learning approaches like classification, regression etc. 
https://archive.ics.uci.edu/ml/datasets.html

**Comment by Merijn-DH** [comment]
Hey! I'm closing this issue because this is in the website repository. I think a better place for this would be Rainbow-Topics, so feel free to add a new issue there (https://github.com/CodingTrain/Rainbow-Topics)!
