### ISSUE TITLE
Agario socket error

### ISSUE THREAD

**Issue by florinpop17** [CodingTrain/website#62]
```
server.js:75
        blob.x = data.x;
               ^

TypeError: Cannot set property 'x' of undefined
```

I'm getting this error on the agario socket challenge.

**Comment by meiamsome** [comment]
Okay, I had a look at this and this can only happen in a few situations:

1. The socket's `update` event occurs prior to the start event. As far as I know, this should never happen.
2. The socket's blob object is removed at some point. This cannot happen in the current code as there is no removal of blobs.

The current code in the repo appears to work fine for me.

Did you make any changes to the code at all?
