### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by tobiasvonarx** [CodingTrain/website#620]
A suggestion to switch to HTTPS encryption, as every website running HTTP will be flagged as "not secure" by browsers in the coming months. 
![image](https://user-images.githubusercontent.com/29151620/41194155-8b2745ea-6c17-11e8-9a06-6fdc3b632e22.png)

![image](https://user-images.githubusercontent.com/29151620/41194171-bb476232-6c17-11e8-87ef-2dbe3f6f609c.png)

**Comment by nilsweb** [comment]
This should definitely be done in the near future but we need to wait for @shiffman since I don't have the necessary privileges to change the settings.

**Comment by meiamsome** [comment]
I set HTTPS up already a couple weeks ago - https://thecodingtrain.com/ - the question is whether or not we want to force HTTPS on the site. I can't really see any downsides except maybe really old browsers? But it's unlikely to have any negatives.

I left it as an option because I don't know why we would prefer to force HTTPS - we don't have any forms or anything like that

**Comment by shiffman** [comment]
I'm happy to force HTTPS. The only issue I think we might run up against is any examples that query a non HTTPS API?

**Comment by tobiasvonarx** [comment]
I agree. The API references in the HTML files would then have to be changed to HTTPS, as mixed content errors between HTTP and HTTPS might occur. CDNs nowadays practically all support HTTPS (cloudflare, cdnjs, etc.), so I assume using their HTTPS equivalent should pose no problem?

**Comment by tobiasvonarx** [comment]
https://github.com/shiffman/shiffman.net/pull/56 is a mixed content error, if HTTPS is introduced all references would have to be changed to HTTPS

**Comment by shiffman** [comment]
I'd gladly accept a pull request to fix all the references!

**Comment by tobiasvonarx** [comment]
I inspected the HTML pages in the repo and didn't find any faulty references. The current HTTPS version works just fine without errors, so I think forcing HTTPS is safe.

**Comment by shiffman** [comment]
I think this can be closed! Let's re-open if I'm wrong.
