### ISSUE TITLE
Barnleys Fern | Enhancement

### ISSUE THREAD

**Issue by DrProfEvil** [CodingTrain/website#624]
Hi,

my name is Tom and I have an enhancement for the barnleys fern. I hope you enjoy it. It will be exciting, if you can improve this project more and more.

Tom

![image](https://user-images.githubusercontent.com/30465861/41373614-1ddb8018-6f51-11e8-82f6-f6b96ae30ad8.png)

[Barnleys Farn.zip](https://github.com/CodingTrain/website/files/2099574/Barnleys.Farn.zip)

**Comment by nilsweb** [comment]
This looks great! If you like, you can add it as a community contribution to the related video.
http://thecodingtrain.com/CodingChallenges/108-barnsley-fern
