### ISSUE TITLE
Coding Challenge-Simulate moral conflict

### ISSUE THREAD

**Issue by Devarun-goswamii** [CodingTrain/website#632]
Create an environment where many vehicles compete with each other to reach a fixed target. When a vehicle reaches the target it gets bigger in size.
Case 1: If it speeds up, it reaches the target first. Its size increases.
Case 2: If it slows down and lets the others reach first,the overall size of the group(including itself) increases. However, this growth is lesser than in the former case.
The probability of reaching the target first is random. However,if it chooses option 2, the growth is guaranteed but much slower. So,the vehicle has to decide which option to choose to reach the maximum possible size in a certain time.
Interested to see if 'moral conflict' can be simulated, where an entity has to decide between being selfish vs working for the greater good.

**Comment by ellocofray** [comment]
Something like https://www.investopedia.com/terms/n/nash-equilibrium.asp ?

**Comment by Devarun-goswamii** [comment]
Yes,it's like the prisoner's dilemma. If this is applied to a random field(using Perlin noise perhaps:refer to [https://youtu.be/XXEK3UEDDIg](url) )could this be simulated as shown in the video.
![download](https://user-images.githubusercontent.com/40355055/41545290-7fd7cb42-7338-11e8-9b68-f4691510adcc.png)
Thanks.

**Comment by meiamsome** [comment]
Closing for CodingTrain/rainbow-topics#1008, please use that repository for topic suggestions.
