### ISSUE TITLE
Randomized Flood Fill

### ISSUE THREAD

**Issue by cundamic** [CodingTrain/website#636]
For each iteration, a point on the fringe is chosen randomly. Any of the four neighbors of the chosen point that are empty are assigned a similar color and added to the fringe.
https://beta.observablehq.com/@mbostock/randomized-flood-fill

**Comment by meiamsome** [comment]
Please use the [Rainbow Topics](https://github.com/CodingTrain/Rainbow-Topics) repository for topic suggestions.
