### ISSUE TITLE
website points to wrong downgit url

### ISSUE THREAD

**Issue by davidfornesm** [CodingTrain/website#638]
#### Issue behavior: 
![captura de pantalla 2018-06-19 a las 10 18 41](https://user-images.githubusercontent.com/27923974/41585387-31bba998-73aa-11e8-9845-f28489c49141.png)
Hitting the "GET THE CODE" button triggers a redirect to downgit, however, there seems to be a malfunction when the downgit url is formed. 
![captura de pantalla 2018-06-19 a las 10 19 33](https://user-images.githubusercontent.com/27923974/41585469-6f1792b6-73aa-11e8-94bb-e1a885e17fab.png)
Causing the user to get the following error:
![captura de pantalla 2018-06-19 a las 10 19 52](https://user-images.githubusercontent.com/27923974/41585480-7a1ca1ec-73aa-11e8-8507-9a24b1dd13d4.png)

#### Expected behavior:
It is expected to get a well formed url, such as: 
![captura de pantalla 2018-06-19 a las 10 22 32](https://user-images.githubusercontent.com/27923974/41585570-c6e2de56-73aa-11e8-832c-20b78af636ab.png)
That will trigger a proper download: 
![captura de pantalla 2018-06-19 a las 10 22 26](https://user-images.githubusercontent.com/27923974/41585559-bf21dfaa-73aa-11e8-985e-057ca9921886.png)

#### Possible solution:
What first came to mind was that the downgit url prefix was wrong, causing the url to be incorrect. So, I began looking inside the following file: https://github.com/CodingTrain/website/blob/master/_config.yml. However the github_download_prefix seemed to be okay.

Furthermore, I noticed that inside the _CodingChallenges folder the files that hold the information for each coding challenged also held a url-ish value under "repository: ". It seems that this value always starts with "/".

Since my understanding of this website's infrastructure is basically zero, I would guess that this repository 'url' is taken and then is added the downgit prefix in someway that is incorrect causing the final link to have a "//" instead of a single one. As such I would suggest to either change all of the files located inside the _CodingChallenges folder or chaging the code that crafts the downgit url.

**Incorrect**
![captura de pantalla 2018-06-19 a las 10 33 10](https://user-images.githubusercontent.com/27923974/41586101-2dcfb322-73ac-11e8-909d-cae6f10b592f.png)

**Correct**
![captura de pantalla 2018-06-19 a las 10 34 19](https://user-images.githubusercontent.com/27923974/41586164-59053dfa-73ac-11e8-8a8c-76da0f73ec70.png)

#### Related posts
#373 

This may be a non-issue or a non-solution (if that were to be the case, im sorry), I don't mean to waste anyones time!

Have a good day!

**Comment by shiffman** [comment]
I like the fact that you can instantly download the code but I wonder if it might make sense to actually have two links? One to the github directory url and one to download, i.e.

[view code](https://github.com/CodingTrain/website/tree/master/CodingChallenges/CC_107_sandpiles), [download code](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/CodingTrain/website/tree/master/CodingChallenges/CC_107_sandpiles)

This would require some design I guess since they are buttons. Simplifying the language would:

```
[code] [download] [demo] 
```

be clear enough?

**Comment by nilsweb** [comment]
Sounds like a good idea! I'll file an issue so we don't forget.
