### ISSUE TITLE
Use Observable for js coding challenge

### ISSUE THREAD

**Issue by buckle2000** [CodingTrain/website#639]
https://beta.observablehq.com/
It is interactive!

**Comment by the349** [comment]
![image](https://user-images.githubusercontent.com/29069199/42108839-a958f8c8-7ba9-11e8-94a0-2c67a3f2d8de.png)
```javascript
<script type="module">
  // Load the Observable runtime and inspector.
  import {Runtime, Inspector} from "https://unpkg.com/@observablehq/notebook-runtime?module";

  // Your notebook, compiled as an ES module.
  import notebook from "https://api.observablehq.com/@jashkenas/my-neat-notebook.js?key=ed62e16955cdc185";

  // Or, your notebook, downloaded locally.
  import notebook from "./my-neat-notebook.js";

  // Load the notebook, observing its cells with a default Inspector
  // that simply renders the value of each cell into the provided DOM node.
  Runtime.load(notebook, Inspector.into(document.body));
</script>
```
### source: [observablehq.com](https://beta.observablehq.com/@jashkenas/downloading-and-embedding-notebooks)

**Comment by nilsweb** [comment]
Closing it now since the P5 Web Editor get used now instead.

**Comment by shiffman** [comment]
Yes! (Noting that I would gladly accept community contribution links to Observable versions of the challenges.) But the p5 editor will be the officially supported one here!
