### ISSUE TITLE
Having a separate link to the related github directory on a video's page

### ISSUE THREAD

**Issue by nilsweb** [CodingTrain/website#654]
As suggested by @shiffman in #638:

> I like the fact that you can instantly download the code but I wonder if it might make sense to actually have two links? One to the github directory url and one to download, i.e.
> 
> [view code](https://github.com/CodingTrain/website/tree/master/CodingChallenges/CC_107_sandpiles), [download code](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/CodingTrain/website/tree/master/CodingChallenges/CC_107_sandpiles)
> 
> This would require some design I guess since they are buttons. Simplifying the language would:
> 
> ```
> [code] [download] [demo] 
> ```
> 
> be clear enough?
>

**Comment by nilsweb** [comment]
Sure, absolutely! 🎉 If you have any questions or run into problems, feel free to ask!

**Comment by MarcoCornejo** [comment]
Yes, how do I set it up on my end? I already forked and have all files locally, but I don't seem to get the site working on my end... Sorry for the rookie question, I'm fairly new to GitHub, but I'm confident I can accomplish this task once I have a local site up and running.

**Comment by MarcoCornejo** [comment]
I can't seem to find the specific file where buttons 'Get Code' and 'View Demo' are created... they belong to class 'code-actions' could you please specify in which files these buttons are created? I managed to add them appropriately once I built the site, but once I shut down the server I lost all the progress... Please specify the files, or perhaps I'm doing something wrong??

This is what it looked like when I did the changes:
![image](https://user-images.githubusercontent.com/12389124/46323547-ba418f80-c5a3-11e8-8338-35e30f081164.png)

**Comment by nilsweb** [comment]
That looks awesome! 🎉
Which file(s) did you modify exactly in order to do this? Normally, you would edit the layout file for videos which is located at `/_jekyll/layouts/video.html`. The corresponding CSS (or SASS in this case) is under `/assets/css/3-layouts/_video.sass` and `/assets/css/2-base/_ctas.sass`.
Just so you know: Everything that gets generated to the `_site` folder is the finished version of the website generated by Jekyll which gets overwritten every time Jekyll runs and should therefor never be modified manually.

**Comment by nilsweb** [comment]
I'm closing this now since it has been successfully implemented. Thanks a lot @MarcoCornejo for this!
