### ISSUE TITLE
P5sound deprecated

### ISSUE THREAD

**Issue by igotapochahontas** [CodingTrain/website#690]
My console. Log is giving me several depreciation errors related to p5sound addon.  I downloaded the newest p5sound.  It says audio Param setter for example.  But there are several other deprecation errors for the web audio API.  (According to my error log)

**Comment by igotapochahontas** [comment]
Log:
MESSAGE: AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018 See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details. LINE: 305 IN: http://192.168.4.86:8080/p5/addons/p5.sound.js LEVEL: WARNING 

MESSAGE: GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details. LINE: 399 IN: http://192.168.4.86:8080/p5/addons/p5.sound.js LEVEL: WARNING 

MESSAGE: The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details. LINE: 46753 IN: http://192.168.4.86:8080/p5/p5.js LEVEL: WARNING 

MESSAGE: The devicemotion event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details. LINE: 46753 IN: http://192.168.4.86:8080/p5/p5.js LEVEL: WARNING

**Comment by shiffman** [comment]
The sound examples are working for me with 0.6.1 I just did a quick test. There are new requirements with the chrome browser for audio and I don't believe you can access the microphone or some other aspects of the HTML5 audio API without `https`.

**Comment by Aakash3** [comment]
**I also have same problem in my Raspberry pi.**
p5.sound.min.js:24 [Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.

p5.sound.min.js:24 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
![how to](https://user-images.githubusercontent.com/33368928/51189308-1a75fa80-1923-11e9-89fd-ddaf1ccdf140.PNG)
