### ISSUE TITLE
Rotation Matrix incorrect for 3D rendering Coding Challenge

### ISSUE THREAD

**Issue by mustafaquraish** [CodingTrain/website#694]
In CC_112_3D_Rendering.pde the following rotation matrix is defined

```
  float[][] rotationY = {
    { cos(angle), 0, -sin(angle)},
    { 0, 1, 0},
    { sin(angle), 0, cos(angle)}
  };
```
It should however be (noticed the signs)

```
  float[][] rotationY = {
    { cos(angle), 0, sin(angle)},
    { 0, 1, 0},
    { -sin(angle), 0, cos(angle)}
  };
```

Otherwise, the rotation happens along a different direction. [Wikipedia](https://en.wikipedia.org/wiki/Rotation_matrix)

**Comment by shiffman** [comment]
Thank you for the fix!
