### ISSUE TITLE
Where did Shiffman code this website

### ISSUE THREAD

**Issue by nobobo1234** [CodingTrain/website#711]
Hey y'all,

Sorry if I'm wrong but I surely remember Shiffman coding this website somewhere on a livestream some time ago, and I was searching for it again. Did he cut it out of the livestream or did he make it private? I'll be very happy if someone can point me to the specific video or livestream.

Thanks in advance!
Nola

**Comment by alexmerlin** [comment]
https://www.youtube.com/user/shiffman/search?query=maze+generator
Look for: Maze Generator with p5.js - Part 1 to 4

**Comment by Samathingamajig** [comment]
i dont know

**Comment by nilsweb** [comment]
I think he first introduced the new system in this stream: https://www.youtube.com/watch?v=iCxqLVm2H3w
