### ISSUE TITLE
LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by markppetty** [CodingTrain/website#719]
Im having some issues getting started.  Any ideas?

64 mac
:/Applications/Processing.app/Contents/Java/core/library:/Users/markpetty/Documents/Processing/libraries/openkinect_processing/library:/Applications/Processing.app/Contents/MacOS/v2/mac
Found path: /Users/markpetty/Documents/Processing/libraries/openkinect_processing/library/v2/mac/
Init Kinect2 
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 6 usb devices connected
[Freenect2Impl] found valid Kinect v2 @20:30 with serial 124678733947
[Freenect2Impl] found 1 devices
1 Device Connected!
[OpenCLDepthPacketProcessor::listDevice]  devices:
  0: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (CPU)[Intel]
  1: Iris (GPU)[Intel]
[OpenCLDepthPacketProcessor::init]  selected device: Iris (GPU)[Intel]
Devce: 0
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 6 usb devices connected
[Freenect2Impl] found valid Kinect v2 @20:30 with serial 124678733947
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -3: LIBUSB_ERROR_ACCESS
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @20:30!
no device connected or failure opening the default one!
EXIT
closing Kinect v2 :

**Comment by gruselhaus** [comment]
Hi @markppetty,
could you please specify your source code? Otherwise it will be hard to find the mistake.

-N
