### ISSUE TITLE
Challenge request - Polyomino & Tetris game

### ISSUE THREAD

**Issue by hounslowcodeclub** [CodingTrain/website#740]
Hi @shiffman 

We use p5.js to teach children programming and we want to teach them how to create visualizations using Polyomino https://en.wikipedia.org/wiki/Polyomino and how to make tetris game using p5.js 

We would really appreciate if you can create an interactive scetch using Polyomino and make tetris game using p5.js in the coding challenge.

Thanks
Volunteers Hounslow Code Club

**Comment by ShivanshuKantPrasad** [comment]
Topics for Coding Challenges are tracked [here.](https://github.com/CodingTrain/Rainbow-Topics)
Add an issue there instead, also check if someone has already added it.
Thanks.

**Comment by nilsweb** [comment]
I've moved it to https://github.com/CodingTrain/Rainbow-Topics/issues/1095
