### ISSUE TITLE
Coding Challenge #24 Isn't Online in its Processing Version.

### ISSUE THREAD

**Issue by LeandrosCatania** [CodingTrain/website#743]
Coding Challenge #24's Processing Version is not uploaded online. Would you please be able to fix this issue, I really wish I could see it and learn how to do it in Processing. Thanks and best regards, Leandros Catania.

**Comment by rlascano** [comment]
Hi check this repo. I'm new on github and I still don't know how to add to the Daniel's repo. https://github.com/rlascano/processing/blob/master/flowfield/
