### ISSUE TITLE
In tutorial 8.6 Regarding retrieval of data

### ISSUE THREAD

**Issue by S530714** [CodingTrain/website#766]
Firstly, Thank you for your videos which are very much useful to us. I had a small doubt i.e.,

I did in the same way as you said I could not load the data in the front end.can you please help me regarding this.

you can find here where did I change in my code:

![screenshot 385](https://user-images.githubusercontent.com/31708972/46981163-c3028d00-d09c-11e8-8158-590f20e10d46.png)
![screenshot 386](https://user-images.githubusercontent.com/31708972/46981164-c3028d00-d09c-11e8-900a-d15de0eac257.png)
![screenshot 387](https://user-images.githubusercontent.com/31708972/46981165-c39b2380-d09c-11e8-85fb-eb6d6af166f7.png)
![screenshot 388](https://user-images.githubusercontent.com/31708972/46981166-c39b2380-d09c-11e8-9f26-89601660d2d7.png)

Here is my overall code:

[gdp.zip](https://github.com/CodingTrain/website/files/2480744/gdp.zip)

**Comment by FriskyDev** [comment]
I am not familiar with this one, but line 12 of `Updateprogram.js` calls loadJSON, and specifies a callback function `finished`, which I don't see defined in the code. When you run this in the browser, you can open the dev tools (in Chrome its F12), and when you pull up or refresh the page you should see an error indicating this.

**Comment by KobeLiesenborgs** [comment]
Hey everyone!

This repository manages the Coding Train website, it isn't the right place for asking questions.
The best things you can do is join [our discord](https://thecodingtrain.com/discord).

P.S. Sorry for the late reply, we didn't use the issue section of this repository for a long while.

Hope to see you there!
