### ISSUE TITLE
Add Code for Challenge 117: Seven Segment Display

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#771]
The seven segment display was done in the p5.js web editor, but it would be nice to have the code [in the Challenges directory here](https://github.com/CodingTrain/website/tree/master/CodingChallenges) for both p5.js and Processing with links from  the challenge  page. Here is the code from the video:

https://editor.p5js.org/codingtrain/sketches/HkP4CF09X

And the markdown for the page:
https://github.com/CodingTrain/website/blob/master/_CodingChallenges/117-seven-segment.md

**Comment by nilsweb** [comment]
Thanks to @mushmula27 and @fernand0aguilar, this should be done now! :tada:
