### ISSUE TITLE
The issue out the Live stream right now!!!

### ISSUE THREAD

**Issue by daanbreur** [CodingTrain/website#784]
![knipsel](https://user-images.githubusercontent.com/32175349/47226385-ab8b1300-d3c0-11e8-82fb-06a6efc7f07d.PNG)

This is the screenshot out the stream

**Comment by daanbreur** [comment]
@shiffman
@nilsweb 

### **This is the Screenshot as a Tasklist**

- [ ] Make View Code => (Github) => (For Processing and P5.js)
- [ ] Make Download Code => (Download Zip) => (For Processing and P5.js)
- [ ] Make Live Example => (Link to P5 Webeditor or Github Pages or Turned Off When Nothing) =>(**ONLY** **P5.js**)

**Comment by ShivanshuKantPrasad** [comment]
Maybe use [Open Processing](https://www.openprocessing.org) for processing(java) projects.

**Comment by nilsweb** [comment]
@daanbreur Thanks for creating a list of what needs to be done!

About your ideas: I'm planning to build a more dynamic (probably Node.JS-based with a _real_ database) version of the website in the future since Jekyll (the system currently used) is more aimed towards static content.

What exactly do you mean by saying "easier way"? What problems did you encounter when adding your own version to the site? Maybe we can improve the current workflow!

**Comment by gruselhaus** [comment]
> What exactly do you mean by saying "easier way"? What problems did you encounter when adding your own version to the site? Maybe we can improve the current workflow!

@daanbreur @nilsweb A workflow for adding community contributions in the frontend would be outstanding. Maybe you could register on thecodingtrain.com and then upload your versions in a nicely designed UI? With a database that would be easy to realize or?

@nilsweb If you need help with database struggles, let me know. This is my daily routine ;)

**Comment by nilsweb** [comment]
@gruselhaus That would be the _ultimate_ goal! Thanks for offering your help, always greatly appreciated! :rocket: What would be the best way to reach out to you for advice?

**Comment by gruselhaus** [comment]
>@gruselhaus That would be the ultimate goal! Thanks for offering your help, always greatly appreciated! 🚀 What would be the best way to reach out to you for advice?

@nilsweb Best by mail to nico.finkernagel@icloud.com. Gladly in German 🗣

**Comment by nilsweb** [comment]
Alright! I'll definitely come back to you! 😜

**Comment by nilsweb** [comment]
I've just found an old PR of mine that tried to solve this issue. Just referencing it here now so I don't forget: #380
