### ISSUE TITLE
Bad Url in CC105 Community Contribution

### ISSUE THREAD

**Issue by gruselhaus** [CodingTrain/website#788]
@sbibow Could you update the url to your Community Contribution in [_CodingChallenges/105-polynomial-regression-tfjs.md](https://github.com/CodingTrain/website/blob/master/_CodingChallenges/105-polynomial-regression-tfjs.md) please?

I think it should be https://sbibow.github.io/coding/p5js%20polynomial%20regression/ instead of https://hablwgq.github.io/coding/p5js%20polynomial%20regression/

Thanks!

-Nico

**Comment by sbibow** [comment]
Thanks for the notice. I changed my username and haven't yet updated all links. 

I will fix it asap.

**Comment by sbibow** [comment]
Pull request is here: #798
