### ISSUE TITLE
Heading levels are skipped

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#789]
(I am running an accessibility audit of the site and will be adding a bunch of issues now.) I'm testing (automated and manually) for [WCAG 2.0 AA](https://www.w3.org/WAI/standards-guidelines/wcag/).

<img width="505" alt="screen shot 2018-10-19 at 2 30 50 pm" src="https://user-images.githubusercontent.com/191758/47237020-d323b080-d3ab-11e8-8340-6bf684e73020.png">

(This is on the homepage).

**Comment by nilsweb** [comment]
This is because normally video cards only appear beneath `h2`s but the latest video card just floats around by itself. Maybe we should convert it into a `span` instead since it is not really a "header"?

**Comment by nilsweb** [comment]
From what I've read on the [WAI homepage](https://www.w3.org/WAI/test-evaluate/preliminary/#headings):
> The heading hierarchy is meaningful. Ideally the page starts with an "h1" — which is usually similar to the page title — and does not skip levels; however, these are not absolute requirements.

So maybe it's now that big of a deal? I really don't know at this point...

**Comment by nilsweb** [comment]
Just found out that on subpages the title uses `h2` instead of `h1`. I have to change that as well.

**Comment by ShivanshuKantPrasad** [comment]
> So maybe it's now that big of a deal? I really don't know at this point...

Heading hierarchy is important for people with screen readers. Screen readers use syntactic tags like headers, footers and link to navigate the page.

**Comment by nilsweb** [comment]
Yes, I totally agree but it's only this one case where a level gets skipped and it only shows up as an "alert" in the testing tool. It would introduce a lot of unnecessary complexity to just fix this...

Headers, footers and navigation tags are used on every page.

**Comment by ShivanshuKantPrasad** [comment]
I guess its fine then.

**Comment by phucduong86** [comment]
I wouldn't rely on one testing tool when it comes to Accessibility. WAVE is great but you might want to run tests through Axe, Tota11y and or pa11y as well. Each tools will shows you slightly different results. 

Regarding the heading hierarchy, it is massively important in term of accessibility, and also SEO.
https://sitechecker.pro/seo-report/http://Shiffman.net

Screen reader in application mode will be fine tabbing through the focusable elements and order in , but in browse/document mode users rely heavily on page heading structure to read through the content. The page should take both of them into consideration.
