### ISSUE TITLE
Form  label is present,  no content

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#790]
(Also on homepage)

<img width="319" alt="screen shot 2018-10-19 at 2 33 25 pm" src="https://user-images.githubusercontent.com/191758/47237072-01a18b80-d3ac-11e8-8866-6b41cb70c93e.png">

>Empty form label
> What It Means
> A form label is present, but does not contain any content.
>  Why It Matters
> A `<label>` element that is associated to a form control but does not contain text will not present any information about the form control to the user.
> How to Fix It
> Ensure that the form label contains text that describes the function of the associated form control. > Labels are not required for image, submit, reset, button, or hidden form controls. If a label is not necessary visually, a descriptive title attribute may be added to the form control.

**Comment by nilsweb** [comment]
This is the toggle button for the mobile navigation. To make the hamburger animated, it was made with three stacked `span`s. I'm not quite sure how we could incorporate text here that is only visible to screen readers... 🤔

**Comment by bjorvack** [comment]
You could use aria-hidden=true this hides the element for a screen reader

**Comment by phucduong86** [comment]
@shiffman  @vimkat  This is issue has been resolved and can be closed.
The button has appropriate aria-label and aria-role. When tested with VoiceOver/NVDA it announces "Open navigation menu"

```
<button id="menu-button" class="mobilenav-toggle" tabindex="0" aria-haspopup="true" aria-controls="global-nav" aria-label="Open navigation menu"> <span></span> <span></span> <span></span> </button>
```

**Comment by shiffman** [comment]
Thank you!!!
