### ISSUE TITLE
New store!

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#796]
I have a new merchandise store.

https://www.designbyhumans.com/shop/codingtrain

We should change the link at the bottom to point to it. I also have this new image in case it's useful:

https://drive.google.com/file/d/18rwiHAi3ySDpw7N8H1G7kwQ4PigEd3Dz/view?usp=sharing

![092718_ct_shophighlight_800x800](https://user-images.githubusercontent.com/191758/47256276-56481380-d44b-11e8-969b-d0509248737c.jpg)

**Comment by nilsweb** [comment]
The new link shouldn't be a problem!
About the image: It might look weird on a white background since the shirts are just "cut off"... 🤔

**Comment by shiffman** [comment]
Yes, I've asked the designer to help make something that fits with the site. More soon!

(Also, I'm doing a pass over the README, CONTRIBUTING, and language on the homepage. Pull request coming soon!)

**Comment by shiffman** [comment]
How is this? 

![102218_ct_shophighlight_alt_800x600](https://user-images.githubusercontent.com/191758/47320211-c2c73c00-d61e-11e8-840e-ef1ce48267db.jpg)

**Comment by nilsweb** [comment]
Yes! That's perfect!

**Comment by shiffman** [comment]
This is now available for anyone to take on. The graphics are here under "promos":

https://drive.google.com/drive/folders/0B_AnqhTfj4qjQmhsOXcxazFGNkU?usp=sharing

**Comment by shiffman** [comment]
Re-opening this as I don't think the image needs some tweaks to fit into the website design. Will be back to report when I have a new one!

<img width="1171" alt="screen shot 2018-10-27 at 8 06 09 pm" src="https://user-images.githubusercontent.com/191758/47679955-eb5db180-db9b-11e8-81cb-56ac272c983b.png">
