### ISSUE TITLE
"see it live" phrasing

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/website#830]
I'm not sure "see it live" is the best language, sounds like maybe it refers to the "live video stream"?  I am struggling to come up with anything better. . .

* browser demo
* run in browser
* run code

Any ideas?

<img width="575" alt="screen shot 2018-10-30 at 3 05 27 pm" src="https://user-images.githubusercontent.com/191758/47743359-469faa80-dc55-11e8-84bb-88c4a42d7c8c.png">

**Comment by nilsweb** [comment]
Some more ideas:
- try it out
- live demo

I also really like "browser demo"!

**Comment by ShivanshuKantPrasad** [comment]
My suggestion is to use `Preview`.
I also like `live demo`.

**Comment by ramsaysewell** [comment]
Maybe `It In Action` ?

**Comment by jonnytest1** [comment]
Im voting for 'LIVE DEMO' (wait is there a vote :P ?)

**Comment by shiffman** [comment]
Still not perfect, but I think "live demo" is an improvement over "see it live!" let's change it until we think of anything better?

**Comment by anuraghazra** [comment]
`view demo` maybe? it's also consistent with the link `view code`
