### ISSUE TITLE
Training a model using feature extractor

### ISSUE THREAD

**Issue by vikasbharadwaj** [CodingTrain/website#851]
I am not able to train the model on more than two different objects. I have created three different buttons and given input to all of them but the model recognises only the first two and not the third one.

[index.txt](https://github.com/CodingTrain/website/files/2571952/index.txt)
[sketch.txt](https://github.com/CodingTrain/website/files/2571953/sketch.txt)

**Comment by shiffman** [comment]
Which version of ml5 are you using? Can you file this at the ml5 library repo? (there may actaully already be on there about this!) Thank you!!
