### ISSUE TITLE
Koch Snowflake - interesting phenomenon or just a mistake?

### ISSUE THREAD

**Issue by tht-jxny** [CodingTrain/website#969]
When i wanted to implement the revised definition of point c of every segment i created a rather interesting figure that looks like this:

![screenshot from 2019-01-02 18-56-04](https://user-images.githubusercontent.com/37499965/50604821-7a4eb900-0ec0-11e9-8ae4-88b4ddf87d91.png)

I always thought that the x-coordinate and the 100+ as the y-coordinate are a bit wrong. Is this just a coincidence? It would be amazing to see an animation that looks a bit like this in a future coding challenge. 

Here is my code snippet (I coded it in javascript):

```
  update() {
    var children = [];
    var v = p5.Vector.sub(this.b, this.a);
    v.div(3);

    //Segment 1
    var a1 = p5.Vector.add(this.a, v);
    children.push(new Segment(this.a, a1));

    //Segment 4
    var b1 = p5.Vector.sub(this.b, v);
    children.push(new Segment(b1, this.b));

    //Segment 2 & 3

		var len = p5.Vector.dist(a1,b1);
		var height = sqrt(3)/2 * len;

    var c = createVector(300,100+height);
    children.push(new Segment(a1, c));
    children.push(new Segment(c, b1));

    return children;
  }
```

**Comment by bb00** [comment]
This is really cool but one thing I'd like to point out is the inefficiency of the code. Instead of constantly redrawing the curve, which would be a load on the GPU, just redraw the curve upon change of the segments array.
